In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sys
import os

project_root = os.path.dirname(os.path.abspath(''))
if project_root not in sys.path:
    sys.path.append(project_root)

from FEATURES.features import *
from BACKTEST.backtest import *
from MODELS.pipeline import *
# from DATA.TOOLS.fetchPlayersStatsV2 import *
from DATA.TOOLS.fetchPlayersStats import *
from DATA.TOOLS.fetchTeamStats import *
from DATA.TOOLS.playerPositions import *

In [12]:
pd.set_option('display.max_columns', None)
    
s19_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S19.csv')
s20_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S20.csv')
s21_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S21.csv')
s22_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S22.csv')
s23_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S23.csv')
s24_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S24.csv')
s25_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S25.csv')
s26_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S26.csv')

df = pd.concat([s19_regular, s20_regular, s21_regular, s22_regular, s23_regular, s24_regular, s25_regular])
df.tail()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_NAME,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,whos_favored,spread,total,team_is_favored,team_spread,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,GP,AGE,FREQ_FG3,FG3M_main,FG3A_main,FG3_PCT_main,NS_FG3_PCT,PLUS_MINUS_FG3,FREQ_FG2,FG2M,FG2A,FG2_PCT,NS_FG2_PCT,PLUS_MINUS_FG2,FREQ_LT_06,FGM_LT_06,FGA_LT_06,LT_06_PCT,NS_LT_06_PCT,PLUS_MINUS_LT_06,FREQ_LT_10,FGM_LT_10,FGA_LT_10,LT_10_PCT,NS_LT_10_PCT,PLUS_MINUS_LT_10,FREQ_GT_15,FGM_GT_15,FGA_GT_15,GT_15_PCT,NS_GT_15_PCT,PLUS_MINUS_GT_15,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,Unnamed: 0.4,Unnamed: 0.3,TEAM_SEASON_ID_x,OPP_BLOWOUT_RISK,OPP_TOV_x,OPP_TOV_y
26301,26301.0,26301,26301,Amir Coffey,1629599,LAC @ GSW,LAC,1610612746,GSW,0,22401198,2025-04-13,W,0,0,1,0,0,NaN,0,0,NaN,0,0,NaN,0,1,0,0,1,-13,0.2,0.000,NaN,NaN,NaN,NaN,11.3,NaN,191.3,-163.9,0.000,0.500,0.167,0.000,0.000,0.0,0.100,0.000,102.32,107.37,-0.083,9.0,89.47,0.113,3.80,4.47,0.30,0.0,1.0,1.0,6.0,0.0,0.0,5.0,0.0,0.0,0.000,0.0,0.0,0.000,1.0,1.0,1.000,0.0,0.0,0.0,0.0,7.0,0.0,5.0,6.0,0.0,1.0,0.0,0,LA Clippers,265,48,86,0.558,14,30,0.467,14,18,0.778,9,33,42,28,11,3,16,21,124,5,91.9,91.9,91.9,1610612744,122.9,117.9,121.4,116.5,119.0,43.0,79.0,0.544,25.0,31.0,11.0,6.0,16.0,0,3.5,218.5,0,-3.5,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,NaN,28.0,0.444,1.28,3.42,0.374,0.369,0.005,0.556,2.43,4.28,0.568,0.541,0.027,0.310,1.54,2.39,0.645,0.629,0.017,0.408,1.86,3.14,0.593,0.584,0.008,0.496,1.47,3.82,0.385,0.375,0.010,1.0,1.0,0.0,0.0,3.0,1.42,1.000,NaN,2.11,0.00,0.00,0.70,0.70,NaN,NaN,22024.0,0.0,NaN,NaN
26302,26302.0,26302,26302,Derrick Jones Jr.,1627884,LAC @ GSW,LAC,1610612746,GSW,0,22401198,2025-04-13,W,3,1,5,1,3,0.333,0,1,0.000,1,2,0.500,1,4,0,0,0,-4,10.5,0.773,0.333333,NaN,NaN,NaN,105.6,NaN,108.6,-5.3,0.063,0.222,0.147,0.091,0.333,0.0,0.098,0.387,95.96,97.43,0.069,35.0,81.19,0.102,17.73,4.11,1.31,4.0,4.0,7.0,15.0,0.0,0.0,11.0,1.0,2.0,0.500,0.0,1.0,0.000,1.0,1.0,1.000,0.0,2.0,0.0,2.0,13.0,0.0,8.0,14.0,0.0,1.0,1.0,0,LA Clippers,265,48,86,0.558,14,30,0.467,14,18,0.778,9,33,42,28,11,3,16,21,124,5,91.9,91.9,91.9,1610612744,122.9,117.9,121.4,116.5,119.0,43.0,79.0,0.544,25.0,31.0,11.0,6.0,16.0,0,3.5,218.5,0,-3.5,0.667,0.333,0.667,0.000,0.00,0.000,0.333,0.000,0.667,1.000,0.000,0.0,0.0,1.000,0.000,NaN,28.0,0.396,1.12,3.39,0.330,0.364,-0.034,0.604,2.86,5.17,0.553,0.540,0.013,0.326,1.97,2.79,0.707,0.634,0.073,0.414,2.26,3.55,0.637,0.585,0.052,0.475,1.38,4.06,0.339,0.372,-0.033,6.0,9.0,3.0,5.0,16.0,7.02,0.667,0.60,2.28,0.00,0.00,0.14,0.43,NaN,NaN,22024.0,0.0,NaN,NaN
26303,26303.0,26303,26303,Buddy Hield,1627741,GSW vs. LAC,GSW,1610612744,LAC,1,22401198,2025-04-13,L,8,0,1,3,7,0.429,2,6,0.333,0,0,NaN,0,1,0,0,0,-6,9.2,1.143,0.571429,NaN,NaN,NaN,99.4,NaN,131.2,-31.0,0.000,0.083,0.040,0.000,0.571,0.0,0.200,0.571,93.20,92.95,0.051,32.0,77.46,0.217,15.75,4.45,1.25,0.0,2.0,2.0,21.0,0.0,0.0,14.0,0.0,1.0,0.000,3.0,6.0,0.500,0.0,0.0,0.000,0.0,0.0,0.0,2.0,5.0,6.0,1.0,22.0,0.0,2.0,0.0,0,Golden State Warriors,265,43,79,0.544,15,33,0.455,18,23,0.783,3,22,25,31,11,6,16,20,119,-5,91.9,91.9,91.9,1610612746,116.5,121.4,117.9,122.9,124.0,48.0,86.0,0.558,42.0,28.0,11.0,3.0,16.0,0,3.5,218.5,1,3.5,0.143,0.857,0.250,0.000,0.75,0.000,0.000,0.000,0.250,1.000,0.000,1.0,0.0,1.000,0.000,NaN,32.0,0.349,1.22,3.35,0.364,0.367,-0.003,0.651,3.41,6.24,0.547,0.538,0.009,0.379,2.26,3.63,0.621,0.628,-0.007,0.493,2.67,4.73,0.564,0.581,-0.016,0.413,1.56,3.96,0.394,0.373,0.021,5.0,8.0,1.0,4.0,12.0,6.24,0.625,0.25,1.92,0.32,0.00,0.16,0.32,NaN,NaN,22024.0,0.0,NaN,NaN
26304,26304.0,26304,26304,Ben Simmons,1627732,LAC @ GSW,LAC,1610612746,GSW,0,22401198,2025-04-13,W,0,1,2,0,0,NaN,0,0,NaN,0,0,NaN,2,0,0,0,1,-11,2.9,0.000,NaN,NaN,NaN,NaN,88.5,NaN,146.8,-57.9,0.200,0.000,0.133,0.167,0.000,1.0,0.040,0.000,86.54,85.90,-0.027,19.0,71.59,0.041,10.62,4.04,0.77,3.0,0.0,3.0,20.0,0.0,1.0,18.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,10.0,0.0,5.0,10.0,0.0,2.0,0.0,0,LA Clippers,265,48,86,0.558,14,30,0.467,14,18,0.778,9,33,42,28,11,3,16,21,124,5,91.9,91.9,91.9,1610612744,122.9,117.9,121.4,116.5,119.0,43.0,79.0,0.544,25.0,31.0,11.0,6.0,16.0,0,3.5,218.5,0,-3.5,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,NaN,28.0,0.381,1.12,3.10,0.361,0.360,0.001,0.619,2.65,5.04,0.525,0.551,-0.025,0.352,1.86,2.86,0.651,0.641,0.009,0.467,2.22,3.80,0.582,0.591,-0.008,0.455,1.33,3.71,0.360,0.366,-0.006,0.0,1.0,0.0,1.0,0.0,3.63,0.000,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,22024.0,0.0,NaN,NaN
26305,26305.0,26305,26305,Jimmy Butler III,202710,GSW vs. LAC,GSW,1610612744,LAC,1,22401198,2025-04-13,L,30,9,1,12,20,0.600,0,2,0.000,6,9,0.667,0,1,1,1,1,2,49.7,1.252,0.600000,F,NaN,NaN,120.5,NaN,120.9,-0.5,0.000,0.028,0.014,0.333,0.600,9.0,0.245,0.626,91.08,89.94,0.137,91.0,74.95,0.252,48.03,4.07,3.49,0.0,4.0,4.0,77.0,1.0,1.0,50.0,6.0,9.0,0.667,6.0,11.0,0.545,1.0,3.0,0.333,11.0,2.0,8.0,22.0,16.0,14.0,5.0,46.0,0.0,1.0,9.0,0,Golden State Warriors,265,43,79,0.544,15,33,0.455,18,23,0.783,3,22,25,31,11,6,16,20,119,-5,91.9,91.9,91.9,1610612746,116.5,121.4,117.9,122.9,124.0,48.0,86.0,0.558,42.0,28.0,11.0,3.0,16.0,0,3.5,218.5,1,3.5,0.900,0.100,0.800,0.067,0.00,0.267,0.200,0.367,0.733,0.667,0.333,0.0,0.0,0.667,0.333,NaN,35.0,0.445,1.78,4.84,0.368,0.361,0.008,0.555,3.40,6.04,0.563,0.539,0.024,0.334,2.36,3.64,0.650,0.627,0.023,0.421,2.71,4.58,0.591,0.582,0.009,0.510,2.09,5.55,0.377,0.369,0.008,10.0,23.0,2.0,10.0,22.0,20.33,0.435,0.20,1.08,0.25,0.05,0.00,0.30,NaN,NaN,22024.0,0.0,NaN,NaN

In [13]:
s26_regular

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,OPP_TOV_x,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV_y
0,0,Brooks Barnhizer,1642964,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,-2,0.0,0.000,NaN,NaN,NaN,60.0,60.0,100.0,100.0,-40.0,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,106.35,106.35,0.000,5,88.63,0.000,2:15,4.70,0.17,0,1,1,1,0,0,1,0,0,0.0,0,0,0.000,0,0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,1.14,0.000,0.000,0.000,0.000,0.00,0.00,0.0,0.00,1.75,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
1,1,Chris Youngblood,1642959,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0.0,0.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,514.29,514.29,0.000,1,428.57,0.000,0:06,3.01,0.01,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
2,2,Cason Wallace,1641717,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,14,5,7,5,10,0.500,3,8,0.375,1,2,0.5,1,6,4,0,2,8,39.9,1.287,0.650000,G,NaN,119.2,119.2,104.9,104.9,14.3,0.023,0.143,0.081,0.179,0.650,2.50,0.140,0.643,91.62,91.62,0.156,78,76.35,0.140,41:39,4.21,2.87,7,10,17,69,0,0,57,2,2,1.0,3,8,0.375,1,2,0.500,6.0,3.0,3.0,4.0,9.0,17.0,2.0,42.0,0.0,3.0,2.0,0.200,0.800,0.286,0.000,0.643,0.214,0.071,0.429,0.286,0.000,1.000,1.0,0.0,0.600,0.400,11.0,28.0,2.0,12.0,26.0,18.05,0.393,0.167,0.393,0.167,1.44,0.22,0.0,0.11,0.06,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
3,3,Jaylin Williams,1631119,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,2,1,0,1,5,0.200,0,4,0.000,0,0,NaN,0,0,1,0,0,-3,6.5,0.400,0.200000,NaN,NaN,96.2,96.2,100.0,100.0,-3.8,0.000,0.000,0.000,0.143,0.200,0.00,0.179,0.200,100.60,100.60,-0.024,26,83.83,0.179,12:53,3.95,0.85,1,2,3,24,0,0,19,0,0,0.0,1,5,0.200,1,1,1.000,0.0,0.0,0.0,0.0,0.0,4.0,0.0,8.0,0.0,1.0,1.0,0.200,0.800,1.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.0,0.0,1.000,0.000,2.0,4.0,0.0,1.0,4.0,6.51,0.500,0.000,0.500,0.000,0.61,0.15,0.0,0.00,0.31,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
4,4,Chet Holmgren,1631096,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,28,2,7,11,17,0.647,2,5,0.400,4,4,1.0,2,5,0,0,3,-1,36.4,1.493,0.705882,F,NaN,122.7,122.7,119.2,119.2,3.4,0.054,0.161,0.103,0.080,0.706,0.67,0.244,0.746,95.38,95.38,0.139,75,79.48,0.244,38:30,4.15,2.58,9,11,20,63,0,1,42,4,5,0.8,7,12,0.583,5,5,1.000,5.0,5.0,3.0,12.0,10.0,14.0,2.0,28.0,1.0,6.0,3.0,0.706,0.294,0.643,0.214,0.214,0.107,0.143,0.179,0.429,0.889,0.111,1.0,0.0,0.909,0.091,8.0,17.0,0.0,3.0,21.0,16.62,0.471,0.000,0.471,0.000,1.26,0.12,0.0,0.12,0.36,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1091,1091,Julian Strawther,1631124,DEN vs. PHX,DEN,1610612743,PHX,1,22500104,2025-10-25,W,3,0,2,1,1,1.000,0,0,NaN,1,2,0.5,0,2,0,0,1,0,4.4,1.596,1.000000,NaN,NaN,125.0,125.0,125.0,125.0,0.0,0.000,0.667,0.667,0.000,1.000,0.00,0.375,0.798,128.72,128.72,0.194,8,107.26,0.375,2:59,4.83,0.26,0,2,2,7,0,0,3,1,1,1.0,0,0,0.000,0,0,0.000,1.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,1.000,0.000,0.667,0.000,0.000,0.000,0.333,0.333,0.667,0.000,1.000,0.0,0.0,0.000,1.000,1.0,1.0,1.0,1.0,3.0,1.13,1.000,1.000,1.000,1.000,2.65,0.00,0.0,0.00,0.00,NaN,22025,Denver Nuggets,2025-10-25,DEN vs. PHX,W,240,43,84,0.512,9,31,0.29,38,42,0.905,11,32,43,31,14,1,16,23,133,22,1,106.6,106.6,106.6,1610612756,123.7,103.3,125.9,105.0,111.0,38.0,88.0,0.432,38.0,24.0,7.0,4.0,20.0
1092,1092,Peyton Watson,1631212,DEN vs. PHX,DEN,1610612743,PHX,1,22500104,2025-10-25,W,7,1,2,3,4,0.750,0,0,NaN,1,1,1.0,1,1,1,0,2,5,11.9,1.577,0.750000,NaN,NaN,141.9,141.9,130.2,130.2,11.6,0.067,0.043,0.053,0.056,0.750,0.50,0.125,0.788,104.15,104.15,0.043,43,86.80,0.125,19:49,4.27,1.37,2,2,4,29,0,0,23,1,2,0.5,2,2,1.000,2,2,1.000,0.0,2.0,3.0,6.0,6.0,5.0,5.0,12.0,0.0,3.0,2.0,1.000,0.000,0.857,0.000,0.000,0.429,0.143,0.000,0.857,0.667,0.333,0.0,0.0,0.667,0.333,2.0,8.0,0.0,6.0,4.0,8.17,0.250,0.000,0.250,0.000,0.49,0.00,0.0,0.00,0.37,NaN,22025,Denver Nuggets,2025-10-25,DEN vs. PHX,W,240,43,84,0.512,9,31,0.29,38,42,0.905,11,32,43,31,14,1,16,23,133,22,1,106.6,106.6,106.6,1610612756,123.7,103.3,125.9,105.0,111.0,38.0,88.0,0.432,38.0,24.0,7.0,4.0,20.0
1093,1093,Khaman Maluach,1642863,PHX @ DEN,PHX,1610612756,DEN,0,22500104,2025-10-25,L,6,1,2,1,3,0.333,0,1,0.000,4,4,1.0,1,1,0,0,1,-1,8.9,1.261,0.333333,NaN,NaN,129.0,129.0,146.4,146.4,-17.4,0.067,0.200,0.100,0.091,0.333,1.00,0.154,0.630,111.94,111.94,0.019,31,93.28,0.154,12:39,4.43,0.91,3,2,5,15,0,0,9,0,1,0.0,1,2,0.500,5,6,0.833,0.0,0.0,0.0,2.0,7.0,2.0,6.0,22.0,1.0,4.0,3.0,0.667,0.333,0.333,0.000,0.000,0.000,0.667,0.000,0.333,1.000,0.000,0.0,0.0,1.000,0.000,5.0,8.0,1.0,3.0,17.0,4.73,0.625,0.333,0.625,0.333,3.59,0.00,0.0,0.21,0.00,NaN,22025,Phoenix Suns,2025-10-25,PHX @ DEN,L,240,38,88,0.432,17,50,0.34,18,22,0.818,12,26,38,24,7,4,20,29,111,-22,1,106.6,106.6,106.6,1610612743,105.0,125.9,103.3,123.7,133.0,43.0,84.0,0.512,43.0,31.0,14.0,1.0,16.0
1094,1094,DaRon Holmes II,1641747,DEN vs. PHX,DEN,1610612743,PHX,1,22500104,2025-10-25,W,3,0,0,1,1,1.000,1,1,1.000,0,0,NaN,0,0,0,0,0,0,3.0,3.000,1.500000,NaN,NaN,125.0,125.0,125.0,125.0,0.0,0.000,0.000,0.000,0.000,1.500,0.00,0.125,1.500,128.72,128.72,0.129,8,107.26,0.125,2:59,5.29,0.29,0,0,0,4,0,0,3,0,0,0.0,1,1,1.000,0,0,0.000,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.000,1.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,0.0,2.0,0.0,2.0,0.0,1.13,0.000,0.000,0.000,0.000,0.00,0.88,0.0,0.00,0.88,NaN,22025,Denver Nuggets,2025-10-25,DEN vs. PHX,W,240,43,84,0.512,9,31,0.29,38,42,0.905,11,32,43,31,14,1,16,23,133,22,1,106.6,106.6,106.6,1610612756,123.7,103.3,125.9,105.0,111.0,38.0,88.0,0.432,38.0,24.0,7.0,4.0,20.0
1095,1095,Rasheer Fleming,1642853,PHX @ DEN,PHX,1610612756,DEN,0,22500104,2025-10-25,L,3,0,2,1,3,0.333,1,2,0.500,0,0,NaN,2,0,0,0,0,-2,5.4,1.000,0.500000,NaN,NaN,100.0,100.0,116.7,116.7,-16.7,0.286,0.000,0.222,0.000,0.500,0.00,0.200,0.500,123.43,123.43,0.093,12,102.86,0.200,4:40,4.74,0.37,2,0,2,6,0,0,3,0,1,0.0,1,2,0.500,0,0,0.000,0.0,0.0,0.0,0.0,5.0,0.0,2.0,6.0,0.0,0.0,0.0,0.333,0.667,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,1.0,1.0,0.0,0.0,2.0,1.77,1.000,0.000,1.000,0.000,1.13,0.00,0.0,0.00,0.00,NaN,22025,Phoenix Suns,2025-10-25,PHX @ DEN,L,240,38,88,0.432,17,50,0.34,18,22,0.818,12,26,38,24,7,4,20,29,111,-22,1,106.6,106.6,106.6,1610612743,105.0,125.9,103.3,123.7,133.0,43.0,84.0,0.512,43.0,31.0,14.0,1.0,16.0

## Fetches Player Gamelogs

In [13]:
# nba = FetchPlayersStats()
# data = nba.getCompleteStats(
#     season='2025-26', 
#     season_type='Regular Season', 
#     sleep_time=2, 
#     max_workers=5,
#     batch_limit=50,
#     complete_cache_file='../DATA/CSV_FILES/REGULAR_DATA/S26.csv'
# )
# data.tail()

Processing 33 games (limited by batch_limit=50)

Processing batch 1/4 (10 games)
Completed batch 1/4

Processing batch 2/4 (10 games)
Completed batch 2/4

Processing batch 3/4 (10 games)
Completed batch 3/4

Processing batch 4/4 (3 games)
Completed batch 4/4
Cache updated. Total games now: 49

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
1091,NaN,Julian Strawther,1631124,DEN vs. PHX,DEN,1610612743,PHX,1,0022500104,2025-10-25,W,3,0,2,1,1,1.000,0,0,NaN,1,2,0.5,0,2,0,0,1,0,4.4,1.596,1.000000,,,125.0,125.0,125.0,125.0,0.0,0.000,0.667,0.667,0.000,1.000,0.0,0.375,0.798,128.72,128.72,0.194,8,107.26,0.375,2:59,4.83,0.26,0,2,2,7,0,0,3,1,1,1.0,0,0,0.0,0,0,0.000,1.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,1.000,0.000,0.667,0.0,0.0,0.000,0.333,0.333,0.667,0.000,1.000,0.0,0.0,0.000,1.000,1.0,1.0,1.0,1.0,3.0,1.13,1.000,1.000,1.000,1.000,2.65,0.00,0.0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1092,NaN,Peyton Watson,1631212,DEN vs. PHX,DEN,1610612743,PHX,1,0022500104,2025-10-25,W,7,1,2,3,4,0.750,0,0,NaN,1,1,1.0,1,1,1,0,2,5,11.9,1.577,0.750000,,,141.9,141.9,130.2,130.2,11.6,0.067,0.043,0.053,0.056,0.750,0.5,0.125,0.788,104.15,104.15,0.043,43,86.80,0.125,19:49,4.27,1.37,2,2,4,29,0,0,23,1,2,0.5,2,2,1.0,2,2,1.000,0.0,2.0,3.0,6.0,6.0,5.0,5.0,12.0,0.0,3.0,2.0,1.000,0.000,0.857,0.0,0.0,0.429,0.143,0.000,0.857,0.667,0.333,0.0,0.0,0.667,0.333,2.0,8.0,0.0,6.0,4.0,8.17,0.250,0.000,0.250,0.000,0.49,0.00,0.0,0.00,0.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093,NaN,Khaman Maluach,1642863,PHX @ DEN,PHX,1610612756,DEN,0,0022500104,2025-10-25,L,6,1,2,1,3,0.333,0,1,0.0,4,4,1.0,1,1,0,0,1,-1,8.9,1.261,0.333333,,,129.0,129.0,146.4,146.4,-17.4,0.067,0.200,0.100,0.091,0.333,1.0,0.154,0.630,111.94,111.94,0.019,31,93.28,0.154,12:39,4.43,0.91,3,2,5,15,0,0,9,0,1,0.0,1,2,0.5,5,6,0.833,0.0,0.0,0.0,2.0,7.0,2.0,6.0,22.0,1.0,4.0,3.0,0.667,0.333,0.333,0.0,0.0,0.000,0.667,0.000,0.333,1.000,0.000,0.0,0.0,1.000,0.000,5.0,8.0,1.0,3.0,17.0,4.73,0.625,0.333,0.625,0.333,3.59,0.00,0.0,0.21,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1094,NaN,DaRon Holmes II,1641747,DEN vs. PHX,DEN,1610612743,PHX,1,0022500104,2025-10-25,W,3,0,0,1,1,1.000,1,1,1.0,0,0,NaN,0,0,0,0,0,0,3.0,3.000,1.500000,,,125.0,125.0,125.0,125.0,0.0,0.000,0.000,0.000,0.000,1.500,0.0,0.125,1.500,128.72,128.72,0.129,8,107.26,0.125,2:59,5.29,0.29,0,0,0,4,0,0,3,0,0,0.0,1,1,1.0,0,0,0.000,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.000,1.000,0.000,0.0,1.0,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,0.0,2.0,0.0,2.0,0.0,1.13,0.000,0.000,0.000,0.000,0.00,0.88,0.0,0.00,0.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1095,NaN,Rasheer Fleming,1642853,PHX @ DEN,PHX,1610612756,DEN,0,0022500104,2025-10-25,L,3,0,2,1,3,0.333,1,2,0.5,0,0,NaN,2,0,0,0,0,-2,5.4,1.000,0.500000,,,100.0,100.0,116.7,116.7,-16.7,0.286,0.000,0.222,0.000,0.500,0.0,0.200,0.500,123.43,123.43,0.093,12,102.86,0.200,4:40,4.74,0.37,2,0,2,6,0,0,3,0,1,0.0,1,2,0.5,0,0,0.000,0.0,0.0,0.0,0.0,5.0,0.0,2.0,6.0,0.0,0.0,0.0,0.333,0.667,0.000,0.0,1.0,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,1.0,1.0,0.0,0.0,2.0,1.77,1.000,0.000,1.000,0.000,1.13,0.00,0.0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Merge team data into player logs

In [ ]:
# # Drop all team-related columns to re-merge with correct pace calculations
# data = s26_regular

# columns_to_drop = [
#     'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
#     # Pace columns (incorrect calculations)
#     'TEAM_PACE', 'GAME_PACE', 'OPP_PACE',
    
#     # Rating columns (may need recalculation with correct pace)
#     'TEAM_OFF_RATING', 'TEAM_DEF_RATING',
#     'OPP_OFF_RATING', 'OPP_DEF_RATING',
    
#     # Other team stats that came from the merge
#     'TEAM_PTS', 'TEAM_FGM', 'TEAM_FGA', 'TEAM_FG_PCT',
#     'TEAM_FG3M', 'TEAM_FG3A', 'TEAM_FG3_PCT',
#     'TEAM_FTM', 'TEAM_FTA', 'TEAM_FT_PCT', 
#     'TEAM_OREB', 'TEAM_DREB', 'TEAM_REB',
#     'TEAM_AST', 'TEAM_STL', 'TEAM_BLK', 'TEAM_TOV',
#     'TEAM_PF', 'TEAM_PLUS_MINUS',
    
#     # Opponent stats
#     'OPP_TEAM_ID', 'OPP_PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
#     'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK', 'OPP_TOV'
    
#     'TEAM_SEASON_ID_x',	'OPP_TOV_x', 'TEAM_SEASON_ID_y', 'OPP_TOV_y', 'TEAM_SEASON_ID', 'TEAM_NAME', 'TEAM_GAME_DATE', 'TEAM_MATCHUP', 'TEAM_WL', 'TEAM_MIN', 'VIDEO_AVAILABLE'
# ]

# # Drop columns that exist in the dataframe
# existing_cols = [col for col in columns_to_drop if col in data.columns]
# data = data.drop(columns=existing_cols)

# teamlogs = mergeTeamtoPlayer(data, season='2025-26', season_type='Regular Season')
# teamlogs

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,OPP_TOV_x,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV_y
0,Brooks Barnhizer,1642964,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,-2,0.0,0.000,NaN,NaN,NaN,60.0,60.0,100.0,100.0,-40.0,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,106.35,106.35,0.000,5,88.63,0.000,2:15,4.70,0.17,0,1,1,1,0,0,1,0,0,0.0,0,0,0.000,0,0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,1.14,0.000,0.000,0.000,0.000,0.00,0.00,0.0,0.00,1.75,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
1,Chris Youngblood,1642959,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0.0,0.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,514.29,514.29,0.000,1,428.57,0.000,0:06,3.01,0.01,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
2,Cason Wallace,1641717,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,14,5,7,5,10,0.500,3,8,0.375,1,2,0.5,1,6,4,0,2,8,39.9,1.287,0.650000,G,NaN,119.2,119.2,104.9,104.9,14.3,0.023,0.143,0.081,0.179,0.650,2.50,0.140,0.643,91.62,91.62,0.156,78,76.35,0.140,41:39,4.21,2.87,7,10,17,69,0,0,57,2,2,1.0,3,8,0.375,1,2,0.500,6.0,3.0,3.0,4.0,9.0,17.0,2.0,42.0,0.0,3.0,2.0,0.200,0.800,0.286,0.000,0.643,0.214,0.071,0.429,0.286,0.000,1.000,1.0,0.0,0.600,0.400,11.0,28.0,2.0,12.0,26.0,18.05,0.393,0.167,0.393,0.167,1.44,0.22,0.0,0.11,0.06,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
3,Jaylin Williams,1631119,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,2,1,0,1,5,0.200,0,4,0.000,0,0,NaN,0,0,1,0,0,-3,6.5,0.400,0.200000,NaN,NaN,96.2,96.2,100.0,100.0,-3.8,0.000,0.000,0.000,0.143,0.200,0.00,0.179,0.200,100.60,100.60,-0.024,26,83.83,0.179,12:53,3.95,0.85,1,2,3,24,0,0,19,0,0,0.0,1,5,0.200,1,1,1.000,0.0,0.0,0.0,0.0,0.0,4.0,0.0,8.0,0.0,1.0,1.0,0.200,0.800,1.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.0,0.0,1.000,0.000,2.0,4.0,0.0,1.0,4.0,6.51,0.500,0.000,0.500,0.000,0.61,0.15,0.0,0.00,0.31,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
4,Chet Holmgren,1631096,OKC vs. HOU,OKC,1610612760,HOU,1,22500001,2025-10-21,W,28,2,7,11,17,0.647,2,5,0.400,4,4,1.0,2,5,0,0,3,-1,36.4,1.493,0.705882,F,NaN,122.7,122.7,119.2,119.2,3.4,0.054,0.161,0.103,0.080,0.706,0.67,0.244,0.746,95.38,95.38,0.139,75,79.48,0.244,38:30,4.15,2.58,9,11,20,63,0,1,42,4,5,0.8,7,12,0.583,5,5,1.000,5.0,5.0,3.0,12.0,10.0,14.0,2.0,28.0,1.0,6.0,3.0,0.706,0.294,0.643,0.214,0.214,0.107,0.143,0.179,0.429,0.889,0.111,1.0,0.0,0.909,0.091,8.0,17.0,0.0,3.0,21.0,16.62,0.471,0.000,0.471,0.000,1.26,0.12,0.0,0.12,0.36,25.0,22025,Oklahoma City Thunder,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.25,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1,97.5,97.5,97.5,1610612745,107.8,106.9,104.5,103.6,124.0,43.0,97.0,0.443,52.0,23.0,6.0,5.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1091,Julian Strawther,1631124,DEN vs. PHX,DEN,1610612743,PHX,1,22500104,2025-10-25,W,3,0,2,1,1,1.000,0,0,NaN,1,2,0.5,0,2,0,0,1,0,4.4,1.596,1.000000,NaN,NaN,125.0,125.0,125.0,125.0,0.0,0.000,0.667,0.667,0.000,1.000,0.00,0.375,0.798,128.72,128.72,0.194,8,107.26,0.375,2:59,4.83,0.26,0,2,2,7,0,0,3,1,1,1.0,0,0,0.000,0,0,0.000,1.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,1.000,0.000,0.667,0.000,0.000,0.000,0.333,0.333,0.667,0.000,1.000,0.0,0.0,0.000,1.000,1.0,1.0,1.0,1.0,3.0,1.13,1.000,1.000,1.000,1.000,2.65,0.00,0.0,0.00,0.00,NaN,22025,Denver Nuggets,2025-10-25,DEN vs. PHX,W,240,43,84,0.512,9,31,0.29,38,42,0.905,11,32,43,31,14,1,16,23,133,22,1,106.6,106.6,106.6,1610612756,123.7,103.3,125.9,105.0,111.0,38.0,88.0,0.432,38.0,24.0,7.0,4.0,20.0
1092,Peyton Watson,1631212,DEN vs. PHX,DEN,1610612743,PHX,1,22500104,2025-10-25,W,7,1,2,3,4,0.750,0,0,NaN,1,1,1.0,1,1,1,0,2,5,11.9,1.577,0.750000,NaN,NaN,141.9,141.9,130.2,130.2,11.6,0.067,0.043,0.053,0.056,0.750,0.50,0.125,0.788,104.15,104.15,0.043,43,86.80,0.125,19:49,4.27,1.37,2,2,4,29,0,0,23,1,2,0.5,2,2,1.000,2,2,1.000,0.0,2.0,3.0,6.0,6.0,5.0,5.0,12.0,0.0,3.0,2.0,1.000,0.000,0.857,0.000,0.000,0.429,0.143,0.000,0.857,0.667,0.333,0.0,0.0,0.667,0.333,2.0,8.0,0.0,6.0,4.0,8.17,0.250,0.000,0.250,0.000,0.49,0.00,0.0,0.00,0.37,NaN,22025,Denver Nuggets,2025-10-25,DEN vs. PHX,W,240,43,84,0.512,9,31,0.29,38,42,0.905,11,32,43,31,14,1,16,23,133,22,1,106.6,106.6,106.6,1610612756,123.7,103.3,125.9,105.0,111.0,38.0,88.0,0.432,38.0,24.0,7.0,4.0,20.0
1093,Khaman Maluach,1642863,PHX @ DEN,PHX,1610612756,DEN,0,22500104,2025-10-25,L,6,1,2,1,3,0.333,0,1,0.000,4,4,1.0,1,1,0,0,1,-1,8.9,1.261,0.333333,NaN,NaN,129.0,129.0,146.4,146.4,-17.4,0.067,0.200,0.100,0.091,0.333,1.00,0.154,0.630,111.94,111.94,0.019,31,93.28,0.154,12:39,4.43,0.91,3,2,5,15,0,0,9,0,1,0.0,1,2,0.500,5,6,0.833,0.0,0.0,0.0,2.0,7.0,2.0,6.0,22.0,1.0,4.0,3.0,0.667,0.333,0.333,0.000,0.000,0.000,0.667,0.000,0.333,1.000,0.000,0.0,0.0,1.000,0.000,5.0,8.0,1.0,3.0,17.0,4.73,0.625,0.333,0.625,0.333,3.59,0.00,0.0,0.21,0.00,NaN,22025,Phoenix Suns,2025-10-25,PHX @ DEN,L,240,38,88,0.432,17,50,0.34,18,22,0.818,12,26,38,24,7,4,20,29,111,-22,1,106.6,106.6,106.6,1610612743,105.0,125.9,103.3,123.7,133.0,43.0,84.0,0.512,43.0,31.0,14.0,1.0,16.0
1094,DaRon Holmes II,1641747,DEN vs. PHX,DEN,1610612743,PHX,1,22500104,2025-10-25,W,3,0,0,1,1,1.000,1,1,1.000,0,0,NaN,0,0,0,0,0,0,3.0,3.000,1.500000,NaN,NaN,125.0,125.0,125.0,125.0,0.0,0.000,0.000,0.000,0.000,1.500,0.00,0.125,1.500,128.72,128.72,0.129,8,107.26,0.125,2:59,5.29,0.29,0,0,0,4,0,0,3,0,0,0.0,1,1,1.000,0,0,0.000,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.000,1.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,0.0,2.0,0.0,2.0,0.0,1.13,0.000,0.000,0.000,0.000,0.00,0.88,0.0,0.00,0.88,NaN,22025,Denver Nuggets,2025-10-25,DEN vs. PHX,W,240,43,84,0.512,9,31,0.29,38,42,0.905,11,32,43,31,14,1,16,23,133,22,1,106.6,106.6,106.6,1610612756,123.7,103.3,125.9,105.0,111.0,38.0,88.0,0.432,38.0,24.0,7.0,4.0,20.0
1095,Rasheer Fleming,1642853,PHX @ DEN,PHX,1610612756,DEN,0,22500104,2025-10-25,L,3,0,2,1,3,0.333,1,2,0.500,0,0,NaN,2,0,0,0,0,-2,5.4,1.000,0.500000,NaN,NaN,100.0,100.0,116.7,116.7,-16.7,0.286,0.000,0.222,0.000,0.500,0.00,0.200,0.500,123.43,123.43,0.093,12,102.86,0.200,4:40,4.74,0.37,2,0,2,6,0,0,3,0,1,0.0,1,2,0.500,0,0,0.000,0.0,0.0,0.0,0.0,5.0,0.0,2.0,6.0,0.0,0.0,0.0,0.333,0.667,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,1.0,1.0,0.0,0.0,2.0,1.77,1.000,0.000,1.000,0.000,1.13,0.00,0.0,0.00,0.00,NaN,22025,Phoenix Suns,2025-10-25,PHX @ DEN,L,240,38,88,0.432,17,50,0.34,18,22,0.818,12,26,38,24,7,4,20,29,111,-22,1,106.6,106.6,106.6,1610612743,105.0,125.9,103.3,123.7,133.0,43.0,84.0,0.512,43.0,31.0,14.0,1.0,16.0

In [11]:
teamlogs.to_csv('../DATA/CSV_FILES/REGULAR_DATA/S26.csv')

## Assign features for regular season data

In [14]:
# Add this line after your current imports
from FEATURES.features import teamContext as features_teamContext

def convert_min_to_float(min_str):
    try:
        if isinstance(min_str, str) and ":" in min_str:
            minutes, seconds = map(int, min_str.split(":"))
            total_minutes = minutes + seconds / 60
            return round(total_minutes, 2)
        elif isinstance(min_str, (int, float)):
            return float(min_str)
        else:
            return 0
    except:
        return 0

def process_season_features(season_df, prop_type, year):
    df = season_df.copy()
    df = sort_data_for_features(df)
    df['STARTING'] = df['START_POSITION'].apply(lambda x: 1 if x in ['G','F','C'] else 0)
    # df['BLOWOUT_RISK'] = (abs(df['spread']) >= 10).astype(int)
    # df['COMPETITIVE_GAME'] = (abs(df['spread']) < 5).astype(int)
    # df['TEAM_IMPLIED_PTS'] = ((df['total'] + df['team_spread']) / 2).round(1)
    
    # Add position data
    cache_file = os.path.join(project_root, 'DATA', 'TOOLS', 'playerInfo.csv')
    df = assign_position_with_cache(df, cache_file=cache_file, max_workers=4, delay_between_requests=1.5)
   
    df = add_rest_day_features(df)
    df['MIN'] = df['MIN'].apply(convert_min_to_float)
    # df, team_mapping = encode_teams_label(df)

    df = rollingAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE', windows=[5,7,10,15,25,40])
    df = statAgainstTeam(df, player_id_col='PLAYER_ID', opp_col='OPP_ABBREVIATION', stat_line=prop_type)
    df = HomeAwayAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE')
    
    # ADD THESE MISSING CALLS:
    df = getPlayerAvgToDateVectorized(df) 
    df = features_teamContext(df)
    df = assign_opponent_team_stats_dict(df)
    df = assign_team_opp_def_by_position(df, min_minutes=15)
    df = addLagFeatures(df)
    df = add_volatility_features(df, windows=[5,7,10,15,25])
    df = add_standard_deviation_features(df)
    # df = add_performance_volatility_categories(df)
    df = add_recent_form_volatility(df)
    df = process_star_players_data(df, min_minutes=20)
    df = add_performance_without_stars_columns(df, min_games=1)
    df = dynamic_defense_ranking(df)
    df = add_opponent_team_rolling_stats(df, windows=[3,5,7,10])
    df = add_opponent_team_form_indicators(df, windows=[3,5,7,10])
    df = expectedPace(df)
    # df = calculate_game_implied_pace(df)
    df = add_interaction_features(df)  

    # Clean up any unwanted columns
    if 'Unnamed: 0' in df.columns:
        df.drop(columns=['Unnamed: 0'], inplace=True)
    if 'Unnamed: 0.1' in df.columns:
        df.drop(columns=['Unnamed: 0.1'], inplace=True)
    return df

prop_types = ['PTS']
# data = [s19_regular,s20_regular, s21_regular,s22_regular,s23_regular,s24_regular,s25_regular]
# seasons = [2019,2020,2021,2022,2023,2024,2025]
data = [s26_regular]
seasons = [2026]

# Pre-define output directory once
output_dir = os.path.join(project_root, 'DATA', 'CSV_FILES', 'TRAIN_DATA')
os.makedirs(output_dir, exist_ok=True)

# Process each season sequentially but with optimized operations
for season_data, year in zip(data, seasons):
    print(f"Processing year {year}...")
    
    # Process features
    processed_data = process_season_features(
        season_data, 
        prop_type='PTS',
        year=year
    )
    
    # Save file
    output_path = os.path.join(output_dir, f'PTS_TRAIN_{str(year)[-2:]}.csv')
    processed_data.to_csv(output_path)
    print(f"Completed {year}")

Processing year 2026...
Loading position cache...
Loaded 1219 players from cache
Found 380 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1219 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Completed 2026