In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from pathlib import Path
import sys
import os

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.utils.team_info import nameDict
from src.utils.nbaPlayerLogs import NBAGameLogs

pd.set_option('display.max_columns', None)

## Fetches Player Gamelogs

In [2]:
# nba = FetchPlayersStats()
# data = nba.getCompleteStats(
#     season='2025-26', 
#     season_type='Regular Season', 
#     sleep_time=2, 
#     max_workers=5,
#     batch_limit=100,
#     complete_cache_file='data/raw/season_stats/S26.csv',
#     include_playbyplay=False
# )
# data.tail()

In [2]:
# df = NBAGameLogs(season='2024-25', season_type='Regular Season').fetch(skip_start_positions=True).build().get_df()
# df.head()

# Session by session — run this repeatedly until all games are done
logs = NBAGameLogs(season='2025-26', season_type='Playoffs')
logs.fetch(batch_size=50, start_position_delay=2.5, start_position_workers=5, checkpoint_path='tracking_checkpoint.csv')

Fetching data for 2025-26 Playoffs...
✓ Player base
✓ Player advanced
✓ Team base
✓ Team advanced
✓ Checkpoint loaded — 7669/36 games already done, 6 remaining

── Batch 1/1 (6 games) ──

2026-04-28 23:23:41,565 [WARNING] Skipped game 0042500155 after retries: 'NoneType' object has no attribute 'get'
2026-04-28 23:23:41,620 [WARNING] Skipped game 0042500125 after retries: 'NoneType' object has no attribute 'get'
2026-04-28 23:23:41,634 [WARNING] Skipped game 0042500115 after retries: 'NoneType' object has no attribute 'get'

  ✓ Batch 1 done — checkpoint saved (201272 rows total)

  ✗ 3 games failed across all batches: ['0042500155', '0042500125', '0042500115']
✓ START_POSITION ready (201272 rows)

In [3]:
df = logs.build().get_df()
def normalize_player_names(frame, col='PLAYER_NAME', mapping=nameDict):
    """Rewrite player names to the canonical form used as keys in ``mapping``.

    ``mapping`` is {desired_name: current_name_in_data}, so we invert it and
    use ``Series.replace`` to swap any matching value back to the key form.
    """
    inv = {v: k for k, v in mapping.items()}
    before = frame[col].isin(inv).sum()
    frame[col] = frame[col].replace(inv)
    print(f"Renamed {before} rows in '{col}'")
    return frame


df = normalize_player_names(df)
df.head()

✓ Built — shape: (818, 173)
Renamed 44 rows in 'PLAYER_NAME'

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM_PG,FGA_PG,START_POSITION,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_TOV,TEAM_STL,TEAM_BLK,TEAM_BLKA,TEAM_PF,TEAM_PFD,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_E_OFF_RATING,TEAM_OFF_RATING,TEAM_E_DEF_RATING,TEAM_DEF_RATING,TEAM_E_NET_RATING,TEAM_NET_RATING,TEAM_AST_PCT,TEAM_AST_TO,TEAM_AST_RATIO,TEAM_OREB_PCT,TEAM_DREB_PCT,TEAM_REB_PCT,TEAM_TM_TOV_PCT,TEAM_EFG_PCT,TEAM_TS_PCT,TEAM_E_PACE,TEAM_PACE,TEAM_PACE_PER40,TEAM_POSS,TEAM_PIE,OPP_TEAM_ID,OPP_OPP_ABBREVIATION_base,OPP_OPP_NAME_base,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_BLKA,OPP_PF,OPP_PFD,OPP_PTS,OPP_PLUS_MINUS,OPP_E_OFF_RATING,OPP_OFF_RATING,OPP_E_DEF_RATING,OPP_DEF_RATING,OPP_E_NET_RATING,OPP_NET_RATING,OPP_AST_PCT,OPP_AST_TO,OPP_AST_RATIO,OPP_OREB_PCT,OPP_DREB_PCT,OPP_REB_PCT,OPP_TM_TOV_PCT,OPP_EFG_PCT,OPP_TS_PCT,OPP_E_PACE,OPP_PACE,OPP_PACE_PER40,OPP_POSS,OPP_PIE
0,2025-26,1628369,Jayson Tatum,Jayson,1610612738,BOS,Boston Celtics,0042500115,2026-04-28T00:00:00,BOS vs. PHI,L,40.600000,8,19,0.421,4,12,0.333,4,7,0.571,3,13,16,4,4,3,0,1,0,3,24,-9,54.2,1,0,54.0,1,40:36,1,105.7,109.9,109.9,123.7,124.1,124.1,-18.0,-14.2,-14.2,0.160,1.00,13.3,0.063,0.382,0.195,13.3,13.3,0.526,0.543,0.277,0.274,96.64,94.58,78.82,94.58,0.155,81,8.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,89,0.404,11,39,0.282,14,23,0.609,15,34,49,25,12.0,6,0,3,17,20,97,-16.0,100.9,103.2,121.3,120.2,-20.4,-17.0,0.694,2.08,18.4,0.300,0.829,0.515,0.128,0.466,0.489,94.6,94.0,78.33,94,0.404,1610612755,PHI,Philadelphia 76ers,39,78,0.500,15,42,0.357,20,23,0.870,5,42,47,24,10.0,5,3,0,20,17,113,16.0,121.3,120.2,100.9,103.2,20.4,17.0,0.615,2.40,19.2,0.171,0.700,0.485,0.106,0.596,0.641,94.6,94.0,78.33,94,0.596
3,2025-26,1628973,Jalen Brunson,Jalen,1610612752,NYK,New York Knicks,0042500125,2026-04-28T00:00:00,NYK vs. ATL,W,34.735000,15,23,0.652,3,5,0.600,6,8,0.750,1,2,3,8,1,0,0,1,4,5,39,23,53.6,0,0,53.0,1,34:44,1,135.7,141.8,141.8,109.4,109.1,109.1,26.4,32.7,32.7,0.421,8.00,22.9,0.040,0.059,0.051,2.9,2.8,0.717,0.735,0.370,0.372,93.86,91.90,76.58,91.90,0.239,67,15.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,79,0.570,11,26,0.423,25,34,0.735,8,40,48,26,11.0,6,6,2,23,26,126,29.0,130.0,134.0,101.6,103.2,28.4,30.9,0.578,2.36,19.5,0.325,0.824,0.604,0.117,0.639,0.670,96.2,94.0,78.33,94,0.661,1610612737,ATL,Atlanta Hawks,37,83,0.446,13,42,0.310,10,17,0.588,5,22,27,25,10.0,7,2,6,26,23,97,-29.0,101.6,103.2,130.0,134.0,-28.4,-30.9,0.676,2.50,19.5,0.176,0.675,0.396,0.106,0.524,0.536,96.2,94.0,78.33,94,0.339
5,2025-26,1630178,Tyrese Maxey,Tyrese,1610612755,PHI,Philadelphia 76ers,0042500115,2026-04-28T00:00:00,PHI @ BOS,W,42.516667,10,18,0.556,3,10,0.300,2,2,1.000,0,10,10,5,2,2,1,0,1,2,25,15,51.5,1,0,49.0,1,42:31,1,119.5,116.7,116.7,97.2,101.2,101.2,22.2,15.4,15.4,0.200,2.50,19.2,0.000,0.182,0.108,7.7,7.7,0.639,0.662,0.233,0.243,94.49,93.70,78.09,93.70,0.186,84,10.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,78,0.500,15,42,0.357,20,23,0.870,5,42,47,24,10.0,5,3,0,20,17,113,16.0,121.3,120.2,100.9,103.2,20.4,17.0,0.615,2.40,19.2,0.171,0.700,0.485,0.106,0.596,0.641,94.6,94.0,78.33,94,0.596,1610612738,BOS,Boston Celtics,36,89,0.404,11,39,0.282,14,23,0.609,15,34,49,25,12.0,6,0,3,17,20,97,-16.0,100.9,103.2,121.3,120.2,-20.4,-17.0,0.694,2.08,18.4,0.300,0.829,0.515,0.128,0.466,0.489,94.6,94.0,78.33,94,0.404
7,2025-26,1641705,Victor Wembanyama,Victor,1610612759,SAS,San Antonio Spurs,0042500155,2026-04-28T00:00:00,SAS vs. POR,W,33.605000,5,7,0.714,1,2,0.500,6,6,1.000,0,14,14,3,1,0,6,0,3,8,17,20,55.3,1,0,47.0,1,33:36,1,122.0,123.2,123.2,90.2,95.6,95.6,31.8,27.6,27.6,0.125,3.00,23.1,0.000,0.311,0.197,7.7,7.3,0.786,0.882,0.133,0.142,101.21,97.84,81.54,97.84,0.276,69,5.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,75,0.547,12,30,0.400,20,29,0.690,7,35,42,27,17.0,5,8,2,24,28,114,19.0,116.6,121.3,95.8,99.0,20.8,22.3,0.659,1.59,20.6,0.289,0.661,0.520,0.181,0.627,0.649,98.4,95.0,79.17,94,0.651,1610612757,POR,Portland Trail Blazers,33,94,0.351,11,47,0.234,18,23,0.783,14,24,38,24,9.0,8,2,8,28,24,95,-19.0,95.8,99.0,116.6,121.3,-20.8,-22.3,0.727,2.67,17.0,0.339,0.711,0.480,0.094,0.410,0.456,98.4,95.0,79.17,96,0.349
9,2025-26,203954,Joel Embiid,Joel,1610612755,PHI,Philadelphia 76ers,0042500115,2026-04-28T00:00:00,PHI @ BOS,W,38.916667,12,23,0.522,0,5,0.000,9,10,0.900,1,3,4,8,3,0,1,0,4,5,33,13,49.8,0,0,47.0,1,38:55,1,121.6,117.7,117.7,101.4,100.0,100.0,20.2,17.7,17.7,0.381,2.67,20.5,0.029,0.068,0.051,7.7,7.8,0.522,0.602,0.373,0.382,95.84,98.06,81.71,98.06,0.157,79,12.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,78,0.500,15,42,0.357,20,23,0.870,5,42,47,24,10.0,5,3,0,20,17,113,16.0,121.3,120.2,100.9,103.2,20.4,17.0,0.615,2.40,19.2,0.171,0.700,0.485,0.106,0.596,0.641,94.6,94.0,78.33,94,0.596,1610612738,BOS,Boston Celtics,36,89,0.404,11,39,0.282,14,23,0.609,15,34,49,25,12.0,6,0,3,17,20,97,-16.0,100.9,103.2,121.3,120.2,-20.4,-17.0,0.694,2.08,18.4,0.300,0.829,0.515,0.128,0.466,0.489,94.6,94.0,78.33,94,0.404

In [4]:
pos = pd.read_csv('/Users/alexgonzalez/Documents/NBA-Prop-Predictor/data/raw/player_positions/nba_2026_players.csv').rename(
    columns={'name_s26': 'PLAYER_NAME', 'pos': 'POS', 'age': 'AGE'}
)
starting_positions = pd.read_csv('tracking_checkpoint.csv')
df = df.merge(pos, on='PLAYER_NAME', how='left')
df['IS_PLAYOFF'] = 1
df.head()

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM_PG,FGA_PG,START_POSITION,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_TOV,TEAM_STL,TEAM_BLK,TEAM_BLKA,TEAM_PF,TEAM_PFD,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_E_OFF_RATING,TEAM_OFF_RATING,TEAM_E_DEF_RATING,TEAM_DEF_RATING,TEAM_E_NET_RATING,TEAM_NET_RATING,TEAM_AST_PCT,TEAM_AST_TO,TEAM_AST_RATIO,TEAM_OREB_PCT,TEAM_DREB_PCT,TEAM_REB_PCT,TEAM_TM_TOV_PCT,TEAM_EFG_PCT,TEAM_TS_PCT,TEAM_E_PACE,TEAM_PACE,TEAM_PACE_PER40,TEAM_POSS,TEAM_PIE,OPP_TEAM_ID,OPP_OPP_ABBREVIATION_base,OPP_OPP_NAME_base,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_BLKA,OPP_PF,OPP_PFD,OPP_PTS,OPP_PLUS_MINUS,OPP_E_OFF_RATING,OPP_OFF_RATING,OPP_E_DEF_RATING,OPP_DEF_RATING,OPP_E_NET_RATING,OPP_NET_RATING,OPP_AST_PCT,OPP_AST_TO,OPP_AST_RATIO,OPP_OREB_PCT,OPP_DREB_PCT,OPP_REB_PCT,OPP_TM_TOV_PCT,OPP_EFG_PCT,OPP_TS_PCT,OPP_E_PACE,OPP_PACE,OPP_PACE_PER40,OPP_POSS,OPP_PIE,name,POS,AGE,IS_PLAYOFF
0,2025-26,1628369,Jayson Tatum,Jayson,1610612738,BOS,Boston Celtics,0042500115,2026-04-28T00:00:00,BOS vs. PHI,L,40.600000,8,19,0.421,4,12,0.333,4,7,0.571,3,13,16,4,4,3,0,1,0,3,24,-9,54.2,1,0,54.0,1,40:36,1,105.7,109.9,109.9,123.7,124.1,124.1,-18.0,-14.2,-14.2,0.160,1.00,13.3,0.063,0.382,0.195,13.3,13.3,0.526,0.543,0.277,0.274,96.64,94.58,78.82,94.58,0.155,81,8.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,89,0.404,11,39,0.282,14,23,0.609,15,34,49,25,12.0,6,0,3,17,20,97,-16.0,100.9,103.2,121.3,120.2,-20.4,-17.0,0.694,2.08,18.4,0.300,0.829,0.515,0.128,0.466,0.489,94.6,94.0,78.33,94,0.404,1610612755,PHI,Philadelphia 76ers,39,78,0.500,15,42,0.357,20,23,0.870,5,42,47,24,10.0,5,3,0,20,17,113,16.0,121.3,120.2,100.9,103.2,20.4,17.0,0.615,2.40,19.2,0.171,0.700,0.485,0.106,0.596,0.641,94.6,94.0,78.33,94,0.596,Jayson Tatum,PF,27.0,1
1,2025-26,1628973,Jalen Brunson,Jalen,1610612752,NYK,New York Knicks,0042500125,2026-04-28T00:00:00,NYK vs. ATL,W,34.735000,15,23,0.652,3,5,0.600,6,8,0.750,1,2,3,8,1,0,0,1,4,5,39,23,53.6,0,0,53.0,1,34:44,1,135.7,141.8,141.8,109.4,109.1,109.1,26.4,32.7,32.7,0.421,8.00,22.9,0.040,0.059,0.051,2.9,2.8,0.717,0.735,0.370,0.372,93.86,91.90,76.58,91.90,0.239,67,15.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,79,0.570,11,26,0.423,25,34,0.735,8,40,48,26,11.0,6,6,2,23,26,126,29.0,130.0,134.0,101.6,103.2,28.4,30.9,0.578,2.36,19.5,0.325,0.824,0.604,0.117,0.639,0.670,96.2,94.0,78.33,94,0.661,1610612737,ATL,Atlanta Hawks,37,83,0.446,13,42,0.310,10,17,0.588,5,22,27,25,10.0,7,2,6,26,23,97,-29.0,101.6,103.2,130.0,134.0,-28.4,-30.9,0.676,2.50,19.5,0.176,0.675,0.396,0.106,0.524,0.536,96.2,94.0,78.33,94,0.339,Jalen Brunson,PG,29.0,1
2,2025-26,1630178,Tyrese Maxey,Tyrese,1610612755,PHI,Philadelphia 76ers,0042500115,2026-04-28T00:00:00,PHI @ BOS,W,42.516667,10,18,0.556,3,10,0.300,2,2,1.000,0,10,10,5,2,2,1,0,1,2,25,15,51.5,1,0,49.0,1,42:31,1,119.5,116.7,116.7,97.2,101.2,101.2,22.2,15.4,15.4,0.200,2.50,19.2,0.000,0.182,0.108,7.7,7.7,0.639,0.662,0.233,0.243,94.49,93.70,78.09,93.70,0.186,84,10.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,78,0.500,15,42,0.357,20,23,0.870,5,42,47,24,10.0,5,3,0,20,17,113,16.0,121.3,120.2,100.9,103.2,20.4,17.0,0.615,2.40,19.2,0.171,0.700,0.485,0.106,0.596,0.641,94.6,94.0,78.33,94,0.596,1610612738,BOS,Boston Celtics,36,89,0.404,11,39,0.282,14,23,0.609,15,34,49,25,12.0,6,0,3,17,20,97,-16.0,100.9,103.2,121.3,120.2,-20.4,-17.0,0.694,2.08,18.4,0.300,0.829,0.515,0.128,0.466,0.489,94.6,94.0,78.33,94,0.404,Tyrese Maxey,PG,25.0,1
3,2025-26,1641705,Victor Wembanyama,Victor,1610612759,SAS,San Antonio Spurs,0042500155,2026-04-28T00:00:00,SAS vs. POR,W,33.605000,5,7,0.714,1,2,0.500,6,6,1.000,0,14,14,3,1,0,6,0,3,8,17,20,55.3,1,0,47.0,1,33:36,1,122.0,123.2,123.2,90.2,95.6,95.6,31.8,27.6,27.6,0.125,3.00,23.1,0.000,0.311,0.197,7.7,7.3,0.786,0.882,0.133,0.142,101.21,97.84,81.54,97.84,0.276,69,5.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,75,0.547,12,30,0.400,20,29,0.690,7,35,42,27,17.0,5,8,2,24,28,114,19.0,116.6,121.3,95.8,99.0,20.8,22.3,0.659,1.59,20.6,0.289,0.661,0.520,0.181,0.627,0.649,98.4,95.0,79.17,94,0.651,1610612757,POR,Portland Trail Blazers,33,94,0.351,11,47,0.234,18,23,0.783,14,24,38,24,9.0,8,2,8,28,24,95,-19.0,95.8,99.0,116.6,121.3,-20.8,-22.3,0.727,2.67,17.0,0.339,0.711,0.480,0.094,0.410,0.456,98.4,95.0,79.17,96,0.349,Victor Wembanyama,C,22.0,1
4,2025-26,203954,Joel Embiid,Joel,1610612755,PHI,Philadelphia 76ers,0042500115,2026-04-28T00:00:00,PHI @ BOS,W,38.916667,12,23,0.522,0,5,0.000,9,10,0.900,1,3,4,8,3,0,1,0,4,5,33,13,49.8,0,0,47.0,1,38:55,1,121.6,117.7,117.7,101.4,100.0,100.0,20.2,17.7,17.7,0.381,2.67,20.5,0.029,0.068,0.051,7.7,7.8,0.522,0.602,0.373,0.382,95.84,98.06,81.71,98.06,0.157,79,12.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,78,0.500,15,42,0.357,20,23,0.870,5,42,47,24,10.0,5,3,0,20,17,113,16.0,121.3,120.2,100.9,103.2,20.4,17.0,0.615,2.40,19.2,0.171,0.700,0.485,0.106,0.596,0.641,94.6,94.0,78.33,94,0.596,1610612738,BOS,Boston Celtics,36,89,0.404,11,39,0.282,14,23,0.609,15,34,49,25,12.0,6,0,3,17,20,97,-16.0,100.9,103.2,121.3,120.2,-20.4,-17.0,0.694,2.08,18.4,0.300,0.829,0.515,0.128,0.466,0.489,94.6,94.0,78.33,94,0.404,Joel Embiid,C,31.0,1

In [5]:
df.to_csv('/Users/alexgonzalez/Documents/NBA-Prop-Predictor/data/raw/playoff_stats/P26.csv')

In [2]:
"""
BettingPros NBA Prop Bets Scraper
Fetches each market separately to get all props.
"""

import requests
import json
import csv
from datetime import date

BASE_URL = "https://api.bettingpros.com/v3/props"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/121.0.0.0 Safari/537.36",
    "Accept": "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "Origin": "https://www.bettingpros.com",
    "Referer": "https://www.bettingpros.com/",
}

MARKET_NAMES = {
    156: "Points",
    151: "Assists",
    157: "Rebounds",
    335: "Pts+Ast",
    336: "Pts+Reb",
    337: "Reb+Ast",
    338: "Pts+Reb+Ast",
    152: "Steals",
    160: "Blocks",
    162: "3-Pointers Made",
}


def fetch_market(target_date: str, market_id: int, limit: int = 100, offset: int = 0) -> dict:
    params = {
        "limit": limit,
        "offset": offset,
        "sport": "NBA",
        "market_id": market_id,
        "date": target_date,
        "include_selections": "false",
        "include_filter_graphs": "false",
        "data_points": 8,
        "min_odds": -1000,
        "max_odds": 1000,
        "ev_threshold_min": -0.4,
        "ev_threshold_max": 0.4,
    }
    resp = requests.get(BASE_URL, headers=HEADERS, params=params, timeout=15)
    resp.raise_for_status()
    return resp.json()


def parse_props(data: dict) -> list[dict]:
    rows = []
    for prop in data.get("props", []):
        proj = prop.get("projection") or {}
        rows.append({
            "player": prop.get("participant", {}).get("name", "Unknown"),
            "prop":   MARKET_NAMES.get(prop.get("market_id"), prop.get("market_id")),
            "line":   prop.get("over", {}).get("line"),
            "proj":   proj.get("value"),
            "side":   proj.get("recommended_side"),
            "diff":   proj.get("diff"),
        })
    return rows


def scrape_all(target_date: str) -> list[dict]:
    all_rows = []

    print(f"Fetching props for {target_date}...")
    for market_id, market_name in MARKET_NAMES.items():
        seen   = set()
        offset = 0

        while True:
            data = fetch_market(target_date, market_id, limit=500, offset=offset)
            rows = parse_props(data)

            if not rows:
                break

            new_rows = []
            for r in rows:
                key = (r["player"], r["prop"], r["line"])
                if key not in seen:
                    seen.add(key)
                    new_rows.append(r)

            if not new_rows:
                break

            all_rows.extend(new_rows)
            offset += 100

        print(f"  {market_name:<20} → {len([r for r in all_rows if r['prop'] == market_name])} props")

    print(f"\n  Total: {len(all_rows)} props")
    return all_rows


def save_csv(rows: list[dict], filename: str):
    if not rows:
        print("No data to save.")
        return
    fieldnames = list(rows[0].keys())
    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Saved {len(rows)} rows → {filename}")


def save_json(rows: list[dict], filename: str):
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2)
    print(f"Saved {len(rows)} rows → {filename}")


from datetime import date, timedelta

START_DATE    = date(2025, 4, 1)
END_DATE      = date(2025, 4, 15)
OUTPUT_FORMAT = "csv"
OUTPUT_NAME   = "nba_props"

current = START_DATE
while current <= END_DATE:
    target = str(current)
    print(f"\n{'='*50}\nProcessing {target}\n{'='*50}")
    
    rows = scrape_all(target)
    
    if rows:
        if OUTPUT_FORMAT in ("csv", "both"):
            save_csv(rows, f"historical_odds/{target}.csv")
        if OUTPUT_FORMAT in ("json", "both"):
            save_json(rows, f"historical_odds/{target}.json")
    else:
        print(f"  No props found for {target}, skipping.")
    
    current += timedelta(days=1)

print("\nDone!")

==================================================
Processing 2025-04-01
==================================================
Fetching props for 2025-04-01...
  Points               → 76 props
  Assists              → 81 props
  Rebounds             → 78 props
  Pts+Ast              → 75 props
  Pts+Reb              → 73 props
  Reb+Ast              → 73 props
  Pts+Reb+Ast          → 72 props
  Steals               → 76 props
  Blocks               → 83 props
  3-Pointers Made      → 76 props

  Total: 763 props

FileNotFoundError: [Errno 2] No such file or directory: 'historical_odds/2025-04-01.csv'