In [16]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from nbaPlayerLogs import NBAGameLogs
from pathlib import Path
import sys
import os

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.utils.team_info import nameDict

pd.set_option('display.max_columns', None)

## Fetches Player Gamelogs

In [2]:
# nba = FetchPlayersStats()
# data = nba.getCompleteStats(
#     season='2025-26', 
#     season_type='Regular Season', 
#     sleep_time=2, 
#     max_workers=5,
#     batch_limit=100,
#     complete_cache_file='data/raw/season_stats/S26.csv',
#     include_playbyplay=False
# )
# data.tail()

In [41]:
# df = NBAGameLogs(season='2024-25', season_type='Regular Season').fetch(skip_start_positions=True).build().get_df()
# df.head()

# Session by session — run this repeatedly until all games are done
logs = NBAGameLogs(season='2025-26', season_type='Playoffs')
logs.fetch(batch_size=50, start_position_delay=2.5, start_position_workers=5, checkpoint_path='tracking_checkpoint.csv')

Fetching data for 2025-26 Playoffs...
✓ Player base
✓ Player advanced
✓ Team base
✓ Team advanced
✓ Checkpoint loaded — 7661/25 games already done, 3 remaining

── Batch 1/1 (3 games) ──

2026-04-25 19:58:11,617 [WARNING] Skipped game 0042500124 after retries: 'NoneType' object has no attribute 'get'
2026-04-25 19:58:11,622 [WARNING] Skipped game 0042500143 after retries: 'NoneType' object has no attribute 'get'
2026-04-25 19:58:11,651 [WARNING] Skipped game 0042500103 after retries: 'NoneType' object has no attribute 'get'

  ✗ 3 games failed across all batches: ['0042500124', '0042500143', '0042500103']
✓ START_POSITION ready (200964 rows)

In [42]:
pos = pd.read_csv('player_positions.csv').rename(
    columns={'name': 'PLAYER_NAME', 'pos': 'POS', 'age': 'AGE'}
)
starting_positions = pd.read_csv('tracking_checkpoint.csv')
df = logs.build().get_df()
df = df.merge(pos, on='PLAYER_NAME', how='left')
df.head()

✓ Built — shape: (552, 173)

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM_PG,FGA_PG,START_POSITION,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_TOV,TEAM_STL,TEAM_BLK,TEAM_BLKA,TEAM_PF,TEAM_PFD,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_E_OFF_RATING,TEAM_OFF_RATING,TEAM_E_DEF_RATING,TEAM_DEF_RATING,TEAM_E_NET_RATING,TEAM_NET_RATING,TEAM_AST_PCT,TEAM_AST_TO,TEAM_AST_RATIO,TEAM_OREB_PCT,TEAM_DREB_PCT,TEAM_REB_PCT,TEAM_TM_TOV_PCT,TEAM_EFG_PCT,TEAM_TS_PCT,TEAM_E_PACE,TEAM_PACE,TEAM_PACE_PER40,TEAM_POSS,TEAM_PIE,OPP_TEAM_ID,OPP_OPP_ABBREVIATION_base,OPP_OPP_NAME_base,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_BLKA,OPP_PF,OPP_PFD,OPP_PTS,OPP_PLUS_MINUS,OPP_E_OFF_RATING,OPP_OFF_RATING,OPP_E_DEF_RATING,OPP_DEF_RATING,OPP_E_NET_RATING,OPP_NET_RATING,OPP_AST_PCT,OPP_AST_TO,OPP_AST_RATIO,OPP_OREB_PCT,OPP_DREB_PCT,OPP_REB_PCT,OPP_TM_TOV_PCT,OPP_EFG_PCT,OPP_TS_PCT,OPP_E_PACE,OPP_PACE,OPP_PACE_PER40,OPP_POSS,OPP_PIE,POS,AGE
0,2025-26,1631094,Paolo Banchero,Paolo,1610612753,ORL,Orlando Magic,0042500103,2026-04-25T00:00:00,ORL vs. DET,W,38.216667,6,17,0.353,2,5,0.400,11,14,0.786,2,10,12,9,3,3,2,4,3,9,25,6,64.9,1,0,58.0,1,38:13,1,112.4,119.0,119.0,107.0,111.4,111.4,5.4,7.6,7.6,0.391,3.00,25.7,0.049,0.263,0.152,8.6,8.5,0.412,0.540,0.283,0.282,104.17,99.22,82.69,99.22,0.200,79,6.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,89,0.404,15,33,0.455,26,33,0.788,14,34,48,22,14.0,8,8,12,24,25,113,8.0,109.2,117.7,103.4,109.4,5.8,8.3,0.611,1.57,15.8,0.393,0.706,0.542,0.146,0.489,0.546,102.5,96.0,80.00,96,0.514,1610612765,DET,Detroit Pistons,37,85,0.435,11,32,0.344,20,24,0.833,10,32,42,24,16.0,6,12,8,25,24,105,-8.0,103.4,109.4,109.2,117.7,-5.8,-8.3,0.649,1.50,17.9,0.294,0.607,0.458,0.167,0.500,0.549,102.5,96.0,80.00,96,0.486,PF,23.0
1,2025-26,1628983,Shai Gilgeous-Alexander,Shai,1610612760,OKC,Oklahoma City Thunder,0042500143,2026-04-25T00:00:00,OKC @ PHX,W,37.933333,15,18,0.833,1,3,0.333,11,12,0.917,1,3,4,8,3,1,0,0,4,9,42,10,58.8,0,0,57.0,1,37:56,1,129.6,124.7,124.7,113.2,113.8,113.8,16.4,10.9,10.9,0.364,2.67,22.9,0.029,0.077,0.054,8.6,8.8,0.861,0.902,0.300,0.309,100.14,101.86,84.89,101.86,0.257,81,15.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,91,0.495,12,37,0.324,19,21,0.905,8,35,43,23,8.0,6,6,2,22,25,121,12.0,120.7,122.2,110.0,111.2,10.7,11.0,0.511,2.88,16.9,0.286,0.776,0.531,0.081,0.560,0.604,99.7,98.5,82.08,99,0.577,1610612756,PHX,Phoenix Suns,38,87,0.437,13,41,0.317,20,23,0.870,9,30,39,25,11.0,2,2,6,25,22,109,-12.0,110.0,111.2,120.7,122.2,-10.7,-11.0,0.658,2.27,18.7,0.224,0.714,0.469,0.112,0.511,0.561,99.7,98.5,82.08,98,0.423,PG,27.0
2,2025-26,1626157,Karl-Anthony Towns,Karl-Anthony,1610612752,NYK,New York Knicks,0042500124,2026-04-25T00:00:00,NYK @ ATL,W,29.311667,6,10,0.600,1,2,0.500,7,9,0.778,3,7,10,10,2,2,0,0,5,9,20,16,51.0,1,1,45.0,1,29:19,1,123.0,123.7,123.7,92.8,90.5,90.5,30.1,33.3,33.3,0.526,5.00,38.5,0.120,0.219,0.175,7.7,7.7,0.650,0.716,0.246,0.252,98.88,99.89,83.24,99.89,0.253,59,6.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,83,0.494,14,31,0.452,18,23,0.783,12,31,43,23,15.0,9,3,5,23,21,114,16.0,118.6,121.3,97.0,104.3,21.6,17.0,0.561,1.53,17.3,0.356,0.608,0.490,0.160,0.578,0.612,98.6,94.0,78.33,94,0.599,1610612737,ATL,Atlanta Hawks,34,83,0.410,10,41,0.244,20,25,0.800,12,26,38,20,19.0,8,5,3,21,23,98,-16.0,97.0,104.3,118.6,121.3,-21.6,-17.0,0.588,1.05,14.9,0.392,0.644,0.510,0.202,0.470,0.521,98.6,94.0,78.33,94,0.401,C,30.0
3,2025-26,1628415,Dillon Brooks,Dillon,1610612756,PHX,Phoenix Suns,0042500143,2026-04-25T00:00:00,PHX vs. OKC,L,36.778333,11,21,0.524,4,9,0.444,7,7,1.000,3,4,7,1,3,0,0,0,5,4,33,-2,39.9,0,0,45.0,1,36:47,1,115.0,117.1,117.1,114.3,118.2,118.2,0.7,-1.1,-1.1,0.050,0.33,3.6,0.079,0.105,0.092,10.7,10.7,0.619,0.685,0.314,0.317,102.43,99.84,83.20,99.84,0.140,76,11.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38,87,0.437,13,41,0.317,20,23,0.870,9,30,39,25,11.0,2,2,6,25,22,109,-12.0,110.0,111.2,120.7,122.2,-10.7,-11.0,0.658,2.27,18.7,0.224,0.714,0.469,0.112,0.511,0.561,99.7,98.5,82.08,98,0.423,1610612760,OKC,Oklahoma City Thunder,45,91,0.495,12,37,0.324,19,21,0.905,8,35,43,23,8.0,6,6,2,22,25,121,12.0,120.7,122.2,110.0,111.2,10.7,11.0,0.511,2.88,16.9,0.286,0.776,0.531,0.081,0.560,0.604,99.7,98.5,82.08,99,0.577,SF,30.0
4,2025-26,1630595,Cade Cunningham,Cade,1610612765,DET,Detroit Pistons,0042500103,2026-04-25T00:00:00,DET @ ORL,L,41.171667,8,23,0.348,3,10,0.300,8,9,0.889,2,3,5,9,9,0,0,3,3,8,27,2,37.5,0,0,44.0,1,41:10,1,109.0,114.5,114.5,107.9,112.0,112.0,1.2,2.4,2.4,0.360,1.00,20.5,0.048,0.064,0.056,20.5,20.0,0.413,0.501,0.365,0.370,101.03,96.77,80.64,96.77,0.082,83,8.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,85,0.435,11,32,0.344,20,24,0.833,10,32,42,24,16.0,6,12,8,25,24,105,-8.0,103.4,109.4,109.2,117.7,-5.8,-8.3,0.649,1.50,17.9,0.294,0.607,0.458,0.167,0.500,0.549,102.5,96.0,80.00,96,0.486,1610612753,ORL,Orlando Magic,36,89,0.404,15,33,0.455,26,33,0.788,14,34,48,22,14.0,8,8,12,24,25,113,8.0,109.2,117.7,103.4,109.4,5.8,8.3,0.611,1.57,15.8,0.393,0.706,0.542,0.146,0.489,0.546,102.5,96.0,80.00,96,0.514,PG,24.0

In [43]:
def normalize_player_names(frame, col='PLAYER_NAME', mapping=nameDict):
    """Rewrite player names to the canonical form used as keys in ``mapping``.

    ``mapping`` is {desired_name: current_name_in_data}, so we invert it and
    use ``Series.replace`` to swap any matching value back to the key form.
    """
    inv = {v: k for k, v in mapping.items()}
    before = frame[col].isin(inv).sum()
    frame[col] = frame[col].replace(inv)
    print(f"Renamed {before} rows in '{col}'")
    return frame


df = normalize_player_names(df)
df.head()

Renamed 29 rows in 'PLAYER_NAME'

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM_PG,FGA_PG,START_POSITION,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_TOV,TEAM_STL,TEAM_BLK,TEAM_BLKA,TEAM_PF,TEAM_PFD,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_E_OFF_RATING,TEAM_OFF_RATING,TEAM_E_DEF_RATING,TEAM_DEF_RATING,TEAM_E_NET_RATING,TEAM_NET_RATING,TEAM_AST_PCT,TEAM_AST_TO,TEAM_AST_RATIO,TEAM_OREB_PCT,TEAM_DREB_PCT,TEAM_REB_PCT,TEAM_TM_TOV_PCT,TEAM_EFG_PCT,TEAM_TS_PCT,TEAM_E_PACE,TEAM_PACE,TEAM_PACE_PER40,TEAM_POSS,TEAM_PIE,OPP_TEAM_ID,OPP_OPP_ABBREVIATION_base,OPP_OPP_NAME_base,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_BLKA,OPP_PF,OPP_PFD,OPP_PTS,OPP_PLUS_MINUS,OPP_E_OFF_RATING,OPP_OFF_RATING,OPP_E_DEF_RATING,OPP_DEF_RATING,OPP_E_NET_RATING,OPP_NET_RATING,OPP_AST_PCT,OPP_AST_TO,OPP_AST_RATIO,OPP_OREB_PCT,OPP_DREB_PCT,OPP_REB_PCT,OPP_TM_TOV_PCT,OPP_EFG_PCT,OPP_TS_PCT,OPP_E_PACE,OPP_PACE,OPP_PACE_PER40,OPP_POSS,OPP_PIE,POS,AGE
0,2025-26,1631094,Paolo Banchero,Paolo,1610612753,ORL,Orlando Magic,0042500103,2026-04-25T00:00:00,ORL vs. DET,W,38.216667,6,17,0.353,2,5,0.400,11,14,0.786,2,10,12,9,3,3,2,4,3,9,25,6,64.9,1,0,58.0,1,38:13,1,112.4,119.0,119.0,107.0,111.4,111.4,5.4,7.6,7.6,0.391,3.00,25.7,0.049,0.263,0.152,8.6,8.5,0.412,0.540,0.283,0.282,104.17,99.22,82.69,99.22,0.200,79,6.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,89,0.404,15,33,0.455,26,33,0.788,14,34,48,22,14.0,8,8,12,24,25,113,8.0,109.2,117.7,103.4,109.4,5.8,8.3,0.611,1.57,15.8,0.393,0.706,0.542,0.146,0.489,0.546,102.5,96.0,80.00,96,0.514,1610612765,DET,Detroit Pistons,37,85,0.435,11,32,0.344,20,24,0.833,10,32,42,24,16.0,6,12,8,25,24,105,-8.0,103.4,109.4,109.2,117.7,-5.8,-8.3,0.649,1.50,17.9,0.294,0.607,0.458,0.167,0.500,0.549,102.5,96.0,80.00,96,0.486,PF,23.0
1,2025-26,1628983,Shai Gilgeous-Alexander,Shai,1610612760,OKC,Oklahoma City Thunder,0042500143,2026-04-25T00:00:00,OKC @ PHX,W,37.933333,15,18,0.833,1,3,0.333,11,12,0.917,1,3,4,8,3,1,0,0,4,9,42,10,58.8,0,0,57.0,1,37:56,1,129.6,124.7,124.7,113.2,113.8,113.8,16.4,10.9,10.9,0.364,2.67,22.9,0.029,0.077,0.054,8.6,8.8,0.861,0.902,0.300,0.309,100.14,101.86,84.89,101.86,0.257,81,15.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,91,0.495,12,37,0.324,19,21,0.905,8,35,43,23,8.0,6,6,2,22,25,121,12.0,120.7,122.2,110.0,111.2,10.7,11.0,0.511,2.88,16.9,0.286,0.776,0.531,0.081,0.560,0.604,99.7,98.5,82.08,99,0.577,1610612756,PHX,Phoenix Suns,38,87,0.437,13,41,0.317,20,23,0.870,9,30,39,25,11.0,2,2,6,25,22,109,-12.0,110.0,111.2,120.7,122.2,-10.7,-11.0,0.658,2.27,18.7,0.224,0.714,0.469,0.112,0.511,0.561,99.7,98.5,82.08,98,0.423,PG,27.0
2,2025-26,1626157,Karl-Anthony Towns,Karl-Anthony,1610612752,NYK,New York Knicks,0042500124,2026-04-25T00:00:00,NYK @ ATL,W,29.311667,6,10,0.600,1,2,0.500,7,9,0.778,3,7,10,10,2,2,0,0,5,9,20,16,51.0,1,1,45.0,1,29:19,1,123.0,123.7,123.7,92.8,90.5,90.5,30.1,33.3,33.3,0.526,5.00,38.5,0.120,0.219,0.175,7.7,7.7,0.650,0.716,0.246,0.252,98.88,99.89,83.24,99.89,0.253,59,6.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,83,0.494,14,31,0.452,18,23,0.783,12,31,43,23,15.0,9,3,5,23,21,114,16.0,118.6,121.3,97.0,104.3,21.6,17.0,0.561,1.53,17.3,0.356,0.608,0.490,0.160,0.578,0.612,98.6,94.0,78.33,94,0.599,1610612737,ATL,Atlanta Hawks,34,83,0.410,10,41,0.244,20,25,0.800,12,26,38,20,19.0,8,5,3,21,23,98,-16.0,97.0,104.3,118.6,121.3,-21.6,-17.0,0.588,1.05,14.9,0.392,0.644,0.510,0.202,0.470,0.521,98.6,94.0,78.33,94,0.401,C,30.0
3,2025-26,1628415,Dillon Brooks,Dillon,1610612756,PHX,Phoenix Suns,0042500143,2026-04-25T00:00:00,PHX vs. OKC,L,36.778333,11,21,0.524,4,9,0.444,7,7,1.000,3,4,7,1,3,0,0,0,5,4,33,-2,39.9,0,0,45.0,1,36:47,1,115.0,117.1,117.1,114.3,118.2,118.2,0.7,-1.1,-1.1,0.050,0.33,3.6,0.079,0.105,0.092,10.7,10.7,0.619,0.685,0.314,0.317,102.43,99.84,83.20,99.84,0.140,76,11.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38,87,0.437,13,41,0.317,20,23,0.870,9,30,39,25,11.0,2,2,6,25,22,109,-12.0,110.0,111.2,120.7,122.2,-10.7,-11.0,0.658,2.27,18.7,0.224,0.714,0.469,0.112,0.511,0.561,99.7,98.5,82.08,98,0.423,1610612760,OKC,Oklahoma City Thunder,45,91,0.495,12,37,0.324,19,21,0.905,8,35,43,23,8.0,6,6,2,22,25,121,12.0,120.7,122.2,110.0,111.2,10.7,11.0,0.511,2.88,16.9,0.286,0.776,0.531,0.081,0.560,0.604,99.7,98.5,82.08,99,0.577,SF,30.0
4,2025-26,1630595,Cade Cunningham,Cade,1610612765,DET,Detroit Pistons,0042500103,2026-04-25T00:00:00,DET @ ORL,L,41.171667,8,23,0.348,3,10,0.300,8,9,0.889,2,3,5,9,9,0,0,3,3,8,27,2,37.5,0,0,44.0,1,41:10,1,109.0,114.5,114.5,107.9,112.0,112.0,1.2,2.4,2.4,0.360,1.00,20.5,0.048,0.064,0.056,20.5,20.0,0.413,0.501,0.365,0.370,101.03,96.77,80.64,96.77,0.082,83,8.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,85,0.435,11,32,0.344,20,24,0.833,10,32,42,24,16.0,6,12,8,25,24,105,-8.0,103.4,109.4,109.2,117.7,-5.8,-8.3,0.649,1.50,17.9,0.294,0.607,0.458,0.167,0.500,0.549,102.5,96.0,80.00,96,0.486,1610612753,ORL,Orlando Magic,36,89,0.404,15,33,0.455,26,33,0.788,14,34,48,22,14.0,8,8,12,24,25,113,8.0,109.2,117.7,103.4,109.4,5.8,8.3,0.611,1.57,15.8,0.393,0.706,0.542,0.146,0.489,0.546,102.5,96.0,80.00,96,0.514,PG,24.0

In [44]:
df.to_csv('/Users/alexgonzalez/Documents/NBA-Prop-Predictor/data/raw/playoff_stats/P26.csv')

In [2]:
"""
BettingPros NBA Prop Bets Scraper
Fetches each market separately to get all props.
"""

import requests
import json
import csv
from datetime import date

BASE_URL = "https://api.bettingpros.com/v3/props"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/121.0.0.0 Safari/537.36",
    "Accept": "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "Origin": "https://www.bettingpros.com",
    "Referer": "https://www.bettingpros.com/",
}

MARKET_NAMES = {
    156: "Points",
    151: "Assists",
    157: "Rebounds",
    335: "Pts+Ast",
    336: "Pts+Reb",
    337: "Reb+Ast",
    338: "Pts+Reb+Ast",
    152: "Steals",
    160: "Blocks",
    162: "3-Pointers Made",
}


def fetch_market(target_date: str, market_id: int, limit: int = 100, offset: int = 0) -> dict:
    params = {
        "limit": limit,
        "offset": offset,
        "sport": "NBA",
        "market_id": market_id,
        "date": target_date,
        "include_selections": "false",
        "include_filter_graphs": "false",
        "data_points": 8,
        "min_odds": -1000,
        "max_odds": 1000,
        "ev_threshold_min": -0.4,
        "ev_threshold_max": 0.4,
    }
    resp = requests.get(BASE_URL, headers=HEADERS, params=params, timeout=15)
    resp.raise_for_status()
    return resp.json()


def parse_props(data: dict) -> list[dict]:
    rows = []
    for prop in data.get("props", []):
        proj = prop.get("projection") or {}
        rows.append({
            "player": prop.get("participant", {}).get("name", "Unknown"),
            "prop":   MARKET_NAMES.get(prop.get("market_id"), prop.get("market_id")),
            "line":   prop.get("over", {}).get("line"),
            "proj":   proj.get("value"),
            "side":   proj.get("recommended_side"),
            "diff":   proj.get("diff"),
        })
    return rows


def scrape_all(target_date: str) -> list[dict]:
    all_rows = []

    print(f"Fetching props for {target_date}...")
    for market_id, market_name in MARKET_NAMES.items():
        seen   = set()
        offset = 0

        while True:
            data = fetch_market(target_date, market_id, limit=500, offset=offset)
            rows = parse_props(data)

            if not rows:
                break

            new_rows = []
            for r in rows:
                key = (r["player"], r["prop"], r["line"])
                if key not in seen:
                    seen.add(key)
                    new_rows.append(r)

            if not new_rows:
                break

            all_rows.extend(new_rows)
            offset += 100

        print(f"  {market_name:<20} → {len([r for r in all_rows if r['prop'] == market_name])} props")

    print(f"\n  Total: {len(all_rows)} props")
    return all_rows


def save_csv(rows: list[dict], filename: str):
    if not rows:
        print("No data to save.")
        return
    fieldnames = list(rows[0].keys())
    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Saved {len(rows)} rows → {filename}")


def save_json(rows: list[dict], filename: str):
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2)
    print(f"Saved {len(rows)} rows → {filename}")


from datetime import date, timedelta

START_DATE    = date(2025, 4, 1)
END_DATE      = date(2025, 4, 15)
OUTPUT_FORMAT = "csv"
OUTPUT_NAME   = "nba_props"

current = START_DATE
while current <= END_DATE:
    target = str(current)
    print(f"\n{'='*50}\nProcessing {target}\n{'='*50}")
    
    rows = scrape_all(target)
    
    if rows:
        if OUTPUT_FORMAT in ("csv", "both"):
            save_csv(rows, f"historical_odds/{target}.csv")
        if OUTPUT_FORMAT in ("json", "both"):
            save_json(rows, f"historical_odds/{target}.json")
    else:
        print(f"  No props found for {target}, skipping.")
    
    current += timedelta(days=1)

print("\nDone!")

==================================================
Processing 2025-04-01
==================================================
Fetching props for 2025-04-01...
  Points               → 76 props
  Assists              → 81 props
  Rebounds             → 78 props
  Pts+Ast              → 75 props
  Pts+Reb              → 73 props
  Reb+Ast              → 73 props
  Pts+Reb+Ast          → 72 props
  Steals               → 76 props
  Blocks               → 83 props
  3-Pointers Made      → 76 props

  Total: 763 props

FileNotFoundError: [Errno 2] No such file or directory: 'historical_odds/2025-04-01.csv'