In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

pd.set_option('display.max_columns', None)
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

from DATA.TOOLS.fetchPlayersStats import FetchPlayersStats
from DATA.TOOLS.fetchTeamStats import *

# feature_path = os.path.abspath(r"C:\Users\alexg\OneDrive\Documents\NBA-Prop-Predictor")
feature_path = os.path.abspath('/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor')
# Add the parent directory to sys.path
if feature_path not in sys.path:
    sys.path.append(feature_path)

from FEATURE_ENGINEERING.features import *
from DATA.TOOLS.playerPositions import *

Features I plan on adding in the future

Player-specific usage and scoring data

- /BoxScoreScoringV2: Breaks down how a player scores (paint, midrange, 3s, free throws). *

Shot quality and location data

- /ShotChartDetail: Individual shot attempts, zones, and frequencies.

- /LeagueDashPlayerShotLocations: Aggregated shot location tendencies.

- /LeagueDashPlayerPtShot: Breaks down shooting by play type and situation.

Opponent and matchup data

- /LeagueDashPtDefend: How defenders contest shots and limit scoring. *

- /LeagueDashTeamStats with defense filters: Opponent’s defensive efficiency.

- /BoxScoreMatchupsV3: Player-vs-player defensive assignments.

Game context and pace

- /ScoreboardV2 or /PlayByPlayV2: For back-to-backs, rest, or pace indicators.

- /TeamDashboardByGeneralSplits: Team-level pace, offensive rating, and context.

In [ ]:
from nba_api.stats.endpoints import boxscorescoringv3
from nba_api.stats.endpoints import boxscorescoringv3
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import random
from requests.exceptions import ReadTimeout, ConnectionError

def fetch_game_data(gameId, sleep_time=1.0):
    """Fetch data for a single game with error handling"""
    try:
        # Add sleep time to avoid rate limiting
        time.sleep(sleep_time)
        
        boxscore = boxscorescoringv3.BoxScoreScoringV3(
            game_id=f'00{gameId}',
            timeout=60
        )
        data_frames = boxscore.get_data_frames()
        
        # Check if we got valid data
        if data_frames and len(data_frames) > 0 and not data_frames[0].empty:
            return data_frames[0], gameId, None
        else:
            return None, gameId, "No data available"
            
    except ReadTimeout:
        return None, gameId, "Timeout"
    except Exception as e:
        return None, gameId, str(e)

# Get unique game IDs
gameIds = s19_regular['GAME_ID'].unique()
games = []
failed_games = []

print(f"Processing {len(gameIds)} games using ThreadPoolExecutor...")

# Use ThreadPoolExecutor with a reasonable number of workers
max_workers = 3  # Start with 3 to avoid overwhelming the API
sleep_time = 1.0  # Sleep time between requests

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    # Submit all tasks
    future_to_game = {
        executor.submit(fetch_game_data, gameId, sleep_time): gameId 
        for gameId in gameIds
    }
    
    # Process completed tasks
    for i, future in enumerate(as_completed(future_to_game), 1):
        gameId = future_to_game[future]
        
        try:
            result, game_id, error = future.result()
            
            if result is not None:
                games.append(result)
                print(f"✓ Game {gameId} completed ({i}/{len(gameIds)})")
            else:
                failed_games.append((gameId, error))
                print(f"✗ Game {gameId} failed: {error} ({i}/{len(gameIds)})")
                
        except Exception as e:
            failed_games.append((gameId, str(e)))
            print(f"✗ Game {gameId} exception: {str(e)} ({i}/{len(gameIds)})")

print(f"\nCompleted!")
print(f"Successfully processed: {len(games)} games")
print(f"Failed games: {len(failed_games)}")

if failed_games:
    print(f"Failed games: {failed_games[:10]}...")

if games:
    games_df = pd.concat(games, ignore_index=True)
    print(f"\nFinal dataset shape: {games_df.shape}")
    games_df.head()
else:
    print("No games were successfully processed!")

Processing 1230 games using ThreadPoolExecutor...
✓ Game 21800002 completed (1/1230)
✓ Game 21800007 completed (2/1230)
✓ Game 21800001 completed (3/1230)
✓ Game 21800012 completed (4/1230)
✓ Game 21800008 completed (5/1230)
✓ Game 21800009 completed (6/1230)
✓ Game 21800003 completed (7/1230)
✓ Game 21800004 completed (8/1230)
✓ Game 21800006 completed (9/1230)
✓ Game 21800013 completed (10/1230)
✓ Game 21800005 completed (11/1230)
✓ Game 21800011 completed (12/1230)
✓ Game 21800010 completed (13/1230)
✓ Game 21800014 completed (14/1230)
✓ Game 21800016 completed (15/1230)
✓ Game 21800015 completed (16/1230)
✓ Game 21800020 completed (17/1230)
✓ Game 21800019 completed (18/1230)
✓ Game 21800022 completed (19/1230)
✓ Game 21800024 completed (20/1230)
✓ Game 21800021 completed (21/1230)
✓ Game 21800025 completed (22/1230)
✓ Game 21800023 completed (23/1230)
✓ Game 21800018 completed (24/1230)
✓ Game 21800017 completed (25/1230)
✓ Game 21800028 completed (26/1230)
✓ Game 21800031 completed (27/1230)
✓ Game 21800033 completed (28/1230)
✓ Game 21800035 completed (29/1230)
✓ Game 21800032 completed (30/1230)
✓ Game 21800030 completed (31/1230)
✓ Game 21800026 completed (32/1230)
✓ Game 21800029 completed (33/1230)
✓ Game 21800034 completed (34/1230)
✓ Game 21800027 completed (35/1230)
✓ Game 21800036 completed (36/1230)
✗ Game 21800038 failed: Timeout (37/1230)
✗ Game 21800037 failed: Timeout (38/1230)
✗ Game 21800039 failed: Timeout (39/1230)
✓ Game 21800040 completed (40/1230)
✓ Game 21800047 completed (41/1230)
✓ Game 21800048 completed (42/1230)
✓ Game 21800042 completed (43/1230)
✓ Game 21800043 completed (44/1230)
✓ Game 21800046 completed (45/1230)
✓ Game 21800041 completed (46/1230)
✓ Game 21800045 completed (47/1230)
✓ Game 21800050 completed (48/1230)
✓ Game 21800051 completed (49/1230)
✓ Game 21800049 completed (50/1230)
✓ Game 21800052 completed (51/1230)
✓ Game 21800053 completed (52/1230)
✓ Game 21800056 completed (53/1230)
✓ Game 21800062 completed (54/1230)
✓ Game 21800057 completed (55/1230)
✓ Game 21800060 completed (56/1230)
✓ Game 21800054 completed (57/1230)
✓ Game 21800059 completed (58/1230)
✓ Game 21800055 completed (59/1230)
✓ Game 21800058 completed (60/1230)
✓ Game 21800061 completed (61/1230)
✓ Game 21800065 completed (62/1230)
✓ Game 21800066 completed (63/1230)
✓ Game 21800064 completed (64/1230)
✓ Game 21800063 completed (65/1230)
✓ Game 21800072 completed (66/1230)
✓ Game 21800067 completed (67/1230)
✓ Game 21800069 completed (68/1230)
✓ Game 21800070 completed (69/1230)
✓ Game 21800071 completed (70/1230)
✓ Game 21800073 completed (71/1230)
✓ Game 21800076 completed (72/1230)
✓ Game 21800077 completed (73/1230)
✓ Game 21800075 completed (74/1230)
✓ Game 21800082 completed (75/1230)
✓ Game 21800081 completed (76/1230)
✓ Game 21800078 completed (77/1230)
✓ Game 21800080 completed (78/1230)
✓ Game 21800079 completed (79/1230)
✓ Game 21800074 completed (80/1230)
✓ Game 21800086 completed (81/1230)
✓ Game 21800085 completed (82/1230)
✓ Game 21800084 completed (83/1230)
✓ Game 21800083 completed (84/1230)
✓ Game 21800088 completed (85/1230)
✓ Game 21800094 completed (86/1230)
✓ Game 21800095 completed (87/1230)
✓ Game 21800091 completed (88/1230)
✓ Game 21800093 completed (89/1230)
✓ Game 21800089 completed (90/1230)
✓ Game 21800092 completed (91/1230)
✓ Game 21800090 completed (92/1230)
✓ Game 21800087 completed (93/1230)
✓ Game 21800097 completed (94/1230)
✓ Game 21800099 completed (95/1230)
✓ Game 21800101 completed (96/1230)
✓ Game 21800103 completed (97/1230)
✓ Game 21800096 completed (98/1230)
✓ Game 21800098 completed (99/1230)
✓ Game 21800100 completed (100/1230)
✓ Game 21800102 completed (101/1230)
✓ Game 21800108 completed (102/1230)
✓ Game 21800106 completed (103/1230)
✓ Game 21800109 completed (104/1230)
✓ Game 21800107 completed (105/1230)
✓ Game 21800104 completed (106/1230)
✓ Game 21800105 completed (107/1230)
✓ Game 21800110 completed (108/1230)
✓ Game 21800114 completed (109/1230)
✓ Game 21800115 completed (110/1230)
✓ Game 21800112 completed (111/1230)
✓ Game 21800116 completed (112/1230)
✗ Game 21800044 failed: Timeout (113/1230)
✓ Game 21800113 completed (114/1230)
✓ Game 21800111 completed (115/1230)
✓ Game 21800120 completed (116/1230)
✓ Game 21800121 completed (117/1230)
✓ Game 21800124 completed (118/1230)
✓ Game 21800118 completed (119/1230)
✓ Game 21800117 completed (120/1230)
✓ Game 21800119 completed (121/1230)
✓ Game 21800123 completed (122/1230)
✓ Game 21800122 completed (123/1230)
✓ Game 21800128 completed (124/1230)
✓ Game 21800127 completed (125/1230)
✓ Game 21800126 completed (126/1230)
✓ Game 21800130 completed (127/1230)
✓ Game 21800129 completed (128/1230)
✓ Game 21800131 completed (129/1230)
✓ Game 21800132 completed (130/1230)
✓ Game 21800125 completed (131/1230)
✓ Game 21800139 completed (132/1230)
✓ Game 21800133 completed (133/1230)
✓ Game 21800138 completed (134/1230)
✓ Game 21800134 completed (135/1230)
✓ Game 21800135 completed (136/1230)
✓ Game 21800137 completed (137/1230)
✓ Game 21800136 completed (138/1230)
✓ Game 21800145 completed (139/1230)
✓ Game 21800142 completed (140/1230)
✗ Game 21800068 failed: Timeout (141/1230)
✓ Game 21800143 completed (142/1230)
✓ Game 21800147 completed (143/1230)
✓ Game 21800141 completed (144/1230)
✓ Game 21800148 completed (145/1230)
✓ Game 21800140 completed (146/1230)
✓ Game 21800146 completed (147/1230)
✓ Game 21800149 completed (148/1230)
✓ Game 21800150 completed (149/1230)
✓ Game 21800152 completed (150/1230)
✓ Game 21800151 completed (151/1230)
✓ Game 21800155 completed (152/1230)
✓ Game 21800153 completed (153/1230)
✓ Game 21800159 completed (154/1230)
✓ Game 21800160 completed (155/1230)
✓ Game 21800158 completed (156/1230)
✓ Game 21800162 completed (157/1230)
✓ Game 21800156 completed (158/1230)
✓ Game 21800154 completed (159/1230)
✓ Game 21800157 completed (160/1230)
✓ Game 21800161 completed (161/1230)
✓ Game 21800164 completed (162/1230)
✓ Game 21800166 completed (163/1230)
✓ Game 21800163 completed (164/1230)
✓ Game 21800165 completed (165/1230)
✓ Game 21800169 completed (166/1230)
✓ Game 21800172 completed (167/1230)
✓ Game 21800171 completed (168/1230)
✓ Game 21800170 completed (169/1230)
✓ Game 21800173 completed (170/1230)
✓ Game 21800167 completed (171/1230)
✓ Game 21800168 completed (172/1230)
✓ Game 21800178 completed (173/1230)
✓ Game 21800176 completed (174/1230)
✓ Game 21800181 completed (175/1230)
✓ Game 21800182 completed (176/1230)
✓ Game 21800180 completed (177/1230)
✓ Game 21800175 completed (178/1230)
✓ Game 21800183 completed (179/1230)
✓ Game 21800177 completed (180/1230)
✓ Game 21800174 completed (181/1230)
✓ Game 21800179 completed (182/1230)
✓ Game 21800189 completed (183/1230)
✓ Game 21800188 completed (184/1230)
✓ Game 21800185 completed (185/1230)
✓ Game 21800187 completed (186/1230)
✓ Game 21800186 completed (187/1230)
✓ Game 21800184 completed (188/1230)
✓ Game 21800192 completed (189/1230)
✓ Game 21800193 completed (190/1230)
✓ Game 21800198 completed (191/1230)
✓ Game 21800191 completed (192/1230)
✓ Game 21800195 completed (193/1230)
✓ Game 21800190 completed (194/1230)
✓ Game 21800196 completed (195/1230)
✓ Game 21800197 completed (196/1230)
✓ Game 21800194 completed (197/1230)
✓ Game 21800201 completed (198/1230)
✓ Game 21800199 completed (199/1230)
✓ Game 21800200 completed (200/1230)
✓ Game 21800204 completed (201/1230)
✓ Game 21800203 completed (202/1230)
✓ Game 21800212 completed (203/1230)
✓ Game 21800205 completed (204/1230)
✓ Game 21800207 completed (205/1230)
✓ Game 21800208 completed (206/1230)
✓ Game 21800209 completed (207/1230)
✓ Game 21800202 completed (208/1230)
✓ Game 21800211 completed (209/1230)
✓ Game 21800206 completed (210/1230)
✓ Game 21800210 completed (211/1230)
✓ Game 21800214 completed (212/1230)
✓ Game 21800213 completed (213/1230)
✓ Game 21800215 completed (214/1230)
✓ Game 21800216 completed (215/1230)
✓ Game 21800223 completed (216/1230)
✓ Game 21800217 completed (217/1230)
✓ Game 21800221 completed (218/1230)
✓ Game 21800219 completed (219/1230)
✓ Game 21800220 completed (220/1230)
✓ Game 21800218 completed (221/1230)
✓ Game 21800222 completed (222/1230)
✓ Game 21800226 completed (223/1230)
✓ Game 21800229 completed (224/1230)
✓ Game 21800230 completed (225/1230)
✓ Game 21800232 completed (226/1230)
✓ Game 21800228 completed (227/1230)
✓ Game 21800231 completed (228/1230)
✓ Game 21800224 completed (229/1230)
✓ Game 21800227 completed (230/1230)
✓ Game 21800225 completed (231/1230)
✓ Game 21800233 completed (232/1230)
✓ Game 21800238 completed (233/1230)
✓ Game 21800235 completed (234/1230)
✓ Game 21800234 completed (235/1230)
✓ Game 21800236 completed (236/1230)
✓ Game 21800237 completed (237/1230)
✓ Game 21800243 completed (238/1230)
✓ Game 21800239 completed (239/1230)
✓ Game 21800240 completed (240/1230)
✓ Game 21800246 completed (241/1230)
✓ Game 21800244 completed (242/1230)
✓ Game 21800245 completed (243/1230)
✓ Game 21800241 completed (244/1230)
✓ Game 21800242 completed (245/1230)
✓ Game 21800247 completed (246/1230)
✓ Game 21800249 completed (247/1230)
✓ Game 21800250 completed (248/1230)
✓ Game 21800251 completed (249/1230)
✓ Game 21800248 completed (250/1230)
✓ Game 21800254 completed (251/1230)
✓ Game 21800255 completed (252/1230)
✓ Game 21800253 completed (253/1230)
✓ Game 21800257 completed (254/1230)
✓ Game 21800261 completed (255/1230)
✓ Game 21800260 completed (256/1230)
✓ Game 21800264 completed (257/1230)
✓ Game 21800256 completed (258/1230)
✗ Game 21800144 failed: Timeout (259/1230)
✓ Game 21800259 completed (260/1230)
✓ Game 21800252 completed (261/1230)
✓ Game 21800263 completed (262/1230)
✓ Game 21800262 completed (263/1230)
✓ Game 21800258 completed (264/1230)
✓ Game 21800270 completed (265/1230)
✓ Game 21800269 completed (266/1230)
✓ Game 21800273 completed (267/1230)
✓ Game 21800276 completed (268/1230)
✓ Game 21800277 completed (269/1230)
✓ Game 21800267 completed (270/1230)
✓ Game 21800266 completed (271/1230)
✓ Game 21800275 completed (272/1230)
✓ Game 21800265 completed (273/1230)
✓ Game 21800272 completed (274/1230)
✓ Game 21800274 completed (275/1230)
✓ Game 21800271 completed (276/1230)
✓ Game 21800278 completed (277/1230)
✓ Game 21800268 completed (278/1230)
✓ Game 21800283 completed (279/1230)
✓ Game 21800279 completed (280/1230)
✓ Game 21800280 completed (281/1230)
✓ Game 21800281 completed (282/1230)
✗ Game 21800282 failed: Timeout (283/1230)
✗ Game 21800285 failed: Timeout (284/1230)
✗ Game 21800284 failed: Timeout (285/1230)
✗ Game 21800288 failed: Timeout (286/1230)
✗ Game 21800286 failed: Timeout (287/1230)
✗ Game 21800290 failed: Timeout (288/1230)
✗ Game 21800289 failed: Timeout (289/1230)
✗ Game 21800291 failed: Timeout (290/1230)
✗ Game 21800287 failed: Timeout (291/1230)

## Fetches Player Gamelogs

In [2]:
# nba = FetchPlayersStats()
# data = nba.getCompleteStats(
#     season='2018-19', 
#     season_type='Regular Season', 
#     sleep_time=1.5, 
#     max_workers=5,
#     batch_limit=100,
#     complete_cache_file='../DATA/CSV_FILES/REGULAR_DATA/S19.csv'
# )
# data.head()

In [3]:
pd.set_option('display.max_columns', None)
def convert_min_to_float(min_str):
    try:
        if isinstance(min_str, str) and ":" in min_str:
            minutes, seconds = map(int, min_str.split(":"))
            total_minutes = minutes + seconds / 60
            return round(total_minutes, 2)
        elif isinstance(min_str, (int, float)):
            return float(min_str)
        else:
            return 0
    except:
        return 0
    

s19_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S19.csv')
s19_regular['IS_PLAYOFF'] = 0
s19_regular['MIN'] = s19_regular['MIN'].apply(convert_min_to_float)

s20_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S20.csv')
s20_regular['IS_PLAYOFF'] = 0
s20_regular['MIN'] = s20_regular['MIN'].apply(convert_min_to_float)

s21_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P21.csv')
s21_playoffs['IS_PLAYOFF'] = 1
s21_playoffs['MIN'] = s21_playoffs['MIN'].apply(convert_min_to_float)
s21_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S21.csv')
s21_regular['IS_PLAYOFF'] = 0
s21_regular['MIN'] = s21_regular['MIN'].apply(convert_min_to_float)
s21 = pd.concat([s21_regular, s21_playoffs])

s22_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P22.csv')
s22_playoffs['IS_PLAYOFF'] = 1
s22_playoffs['MIN'] = s22_playoffs['MIN'].apply(convert_min_to_float)
s22_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S22.csv')
s22_regular['IS_PLAYOFF'] = 0
s22_regular['MIN'] = s22_regular['MIN'].apply(convert_min_to_float)
s22 = pd.concat([s22_regular, s22_playoffs])

s23_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P23.csv')
s23_playoffs['IS_PLAYOFF'] = 1
s23_playoffs['MIN'] = s23_playoffs['MIN'].apply(convert_min_to_float)
s23_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S23.csv')
s23_regular['IS_PLAYOFF'] = 0
s23_regular['MIN'] = s23_regular['MIN'].apply(convert_min_to_float)
s23 = pd.concat([s23_regular, s23_playoffs])

s24_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P24.csv')
s24_playoffs['IS_PLAYOFF'] = 1
s24_playoffs['MIN'] = s24_playoffs['MIN'].apply(convert_min_to_float)
s24_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S24.csv')
s24_regular['IS_PLAYOFF'] = 0
s24_regular['MIN'] = s24_regular['MIN'].apply(convert_min_to_float)
s24 = pd.concat([s24_regular, s24_playoffs])

s25_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P25.csv')
s25_playoffs['IS_PLAYOFF'] = 1
s25_playoffs['MIN'] = s25_playoffs['MIN'].apply(convert_min_to_float)
s25_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S25.csv')
s25_regular['IS_PLAYOFF'] = 0
s25_regular['MIN'] = s25_regular['MIN'].apply(convert_min_to_float)
s25 = pd.concat([s25_regular, s25_playoffs])
s19_regular

,Unnamed: 0.1,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,whos_favored,spread,total,team_is_favored,team_spread
0,0,0,Daniel Theis,1628464,BOS vs. PHI,BOS,1610612738,PHI,1,21800001,2018-10-16,W,0,0,1,0,0,NaN,0,0,NaN,0,0,NaN,0,1,0,0,0,3,1.2,0.000,NaN,NaN,NaN,111.1,111.1,70.0,70.0,41.1,0.000,0.200,0.111,0.000,0.000,0.00,0.000,0.000,110.32,110.32,0.000,9.0,91.94,0.000,4.13,4.23,0.32,2,3,4,3,0,0,3,0,0,0.00,0,0,0.000,1,1,1.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0,22018,Boston Celtics,2018-10-16,BOS vs. PHI,W,240,42,97,0.433,11,37,0.297,10,14,0.714,12,43,55,21,7,5,15,20,105,18,1,106.6,106.6,106.6,1610612755,98.9,82.0,98.0,81.2,87.0,34.0,87.0,0.391,47.0,18.0,8.0,5.0,16.0,home,4.5,211.5,True,4.5
1,1,1,Klay Thompson,202691,GSW vs. OKC,GSW,1610612744,OKC,1,21800002,2018-10-16,W,14,0,4,5,20,0.250,1,8,0.125,3,3,1.000,1,3,0,0,2,2,16.8,0.657,0.275000,G,NaN,106.7,106.7,102.6,102.6,4.0,0.026,0.067,0.048,0.000,0.275,0.00,0.250,0.328,103.59,103.59,-0.021,75.0,86.33,0.250,34.98,4.35,2.72,3,5,8,45,0,0,22,0,6,0.00,5,14,0.357,2,2,1.000,3.0,2.0,0.0,4.0,18.0,14.0,8.0,26.0,2.0,3.0,3.0,0,22018,Golden State Warriors,2018-10-16,GSW vs. OKC,W,240,42,95,0.442,7,26,0.269,17,18,0.944,17,41,58,28,7,7,21,29,108,8,1,106.6,106.6,106.6,1610612760,101.0,93.5,101.6,94.1,100.0,33.0,91.0,0.363,45.0,21.0,12.0,6.0,15.0,home,12.0,220.5,True,12.0
2,2,2,Draymond Green,203110,GSW vs. OKC,GSW,1610612744,OKC,1,21800002,2018-10-16,W,2,5,13,1,6,0.167,0,1,0.000,0,0,NaN,1,12,3,0,6,2,28.1,0.333,0.166667,F,NaN,100.0,100.0,94.8,94.8,5.2,0.033,0.279,0.178,0.185,0.167,0.83,0.143,0.167,111.39,111.39,0.071,75.0,92.82,0.143,32.75,4.05,2.37,6,20,22,79,1,1,62,1,4,0.25,0,2,0.000,2,3,0.667,0.0,0.0,0.0,2.0,14.0,10.0,8.0,20.0,1.0,3.0,1.0,0,22018,Golden State Warriors,2018-10-16,GSW vs. OKC,W,240,42,95,0.442,7,26,0.269,17,18,0.944,17,41,58,28,7,7,21,29,108,8,1,106.6,106.6,106.6,1610612760,101.0,93.5,101.6,94.1,100.0,33.0,91.0,0.363,45.0,21.0,12.0,6.0,15.0,home,12.0,220.5,True,12.0
3,3,3,Alfonzo McKinnie,1628035,GSW vs. OKC,GSW,1610612744,OKC,1,21800002,2018-10-16,W,0,0,0,0,1,0.000,0,1,0.000,0,0,NaN,0,0,0,0,0,-1,0.0,0.000,0.000000,NaN,NaN,80.0,80.0,83.3,83.3,-3.3,0.000,0.000,0.000,0.000,0.000,0.00,0.200,0.000,112.34,112.34,-0.143,5.0,93.62,0.200,2.35,4.38,0.18,0,0,0,2,0,0,1,0,0,0.00,0,1,0.000,0,0,0.000,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0,22018,Golden State Warriors,2018-10-16,GSW vs. OKC,W,240,42,95,0.442,7,26,0.269,17,18,0.944,17,41,58,28,7,7,21,29,108,8,1,106.6,106.6,106.6,1610612760,101.0,93.5,101.6,94.1,100.0,33.0,91.0,0.363,45.0,21.0,12.0,6.0,15.0,home,12.0,220.5,True,12.0
4,4,4,JJ Redick,200755,PHI @ BOS,PHI,1610612755,BOS,0,21800001,2018-10-16,L,16,1,2,7,17,0.412,2,8,0.250,0,0,NaN,0,2,0,0,0,-10,19.9,0.941,0.470588,NaN,NaN,82.9,82.9,100.0,100.0,-17.1,0.000,0.057,0.029,0.063,0.471,0.00,0.224,0.471,111.27,111.27,0.080,70.0,92.72,0.224,29.77,4.49,2.42,0,4,4,39,1,0,20,1,2,0.50,6,15,0.400,1,2,0.500,0.0,0.0,0.0,2.0,10.0,5.0,6.0,20.0,1.0,1.0,2.0,0,22018,Philadelphia 76ers,2018-10-16,PHI @ BOS,L,240,34,87,0.391,5,26,0.192,14,23,0.609,6,41,47,18,8,5,16,20,87,-18,1,106.6,106.6,106.6,1610612738,81.2,98.0,82.0,98.9,105.0,42.0,97.0,0.433,55.0,21.0,7.0,5.0,15.0,home,4.5,211.5,False,-4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26096,26096,26096,Aaron Holiday,1628988,IND @ ATL,IND,1610612754,ATL,0,21801220,2019-04-10,W,13,2,1,5,11,0.455,1,5,0.200,2,3,0.667,0,1,2,0,1,3,22.2,1.055,0.500000,NaN,NaN,125.0,125.0,117.0,117.0,8.0,0.000,0.033,0.019,0.111,0.500,2.00,0.236,0.528,112.25,112.25,0.046,52.0,93.54,0.236,22.45,4.24,1.68,2,6,8,39,0,1,23,3,5,0.60,2,6,0.333,0,0,0.000,3.0,0.0,3.0,8.0,0.0,16.0,8.0,30.0,1.0,5.0,2.0,0,22018,Indiana Pacers,2019-04-10,IND @ ATL,W,240,45,98,0.459,12,30,0.400,33,39,0.846,13,30,43,22,12,7,8,28,135,1,1,112.4,112.4,112.4,1610612737,122.5,121.6,117.7,116.8,134.0,43.0,103.0,0.417,61.0,29.0,5.0,7.0,17.0,home,5.0,225.5,False,-5.0
26097,26097,26097,Mike Scott,203118,PHI vs. CHI,PHI,1610612755,CHI,1,21801224,2019-04-10,W,7,1,7,3,6,0.500,1,1,1.000,0,0,NaN,0,7,0,1,0,21,19.9,1.167,0.583333,F,NaN,144.2,144.2,100.0,100.0,44.2,0.000,0.259,0.159,0.042,0.583,0.00,0.130,0.583,91.91,91.91,0.101,43.0,76.60,0.130,21.93,4.26,1.60,1,10,11,32,0,0,26,0,3,0.00,3,3,1.000,0,0,0.000,0.0,0.0,0.0,2.0,0.0,2.0,8.0,20.0,1.0,1.0,0.0,0,22018,Philadelphia 76ers,2019-04-10,PHI vs. CHI,W,240,52,93,0.559,12,26,0.462,9,15,0.600,9,38,47,30,4,10,7,11,125,16,1,99.1,99.1,99.1,1610612741,128.1,111.7,124.3,108.3,109.0,45.0,95.0,0.474,39.0,21.0,4.0,3.0,8.0,home,6.0,218.5,True,6.0
26098,26098,26098,Willie Cauley-Stein,1626161,SAC @ POR,SAC,1610612758,POR,0,21801230,2019-04-10,L,8,0,5,3,3,1.000,0,0,NaN,2,2,1.000,2,3,0,0,0,16,14.0,2.062,1.000000,C,NaN,170.3,170.3,127.0,127.0,43.2,0.200,0.214,0.208,0.000,1.000,0.00,0.098,1.031,102.46,102.46,0.093,37.0,85.38,0.098,17.33,4.00,1.22,4,5,9,16,0,0,12,1,1,1.00,2,2,1.000,1,2,0.500,0.0,2.0,0.0,6.0,1.0,4.0,0.0,14.0,0.0,2.0,1.0,0,22018,Sacramento Kings,2019-04-10,SAC @ POR,L,240,50,96,0.521,18,43,0.419,13,16,0.813,12,23,35,25,5,1,10,17,131,-5,1,100.4,100.4,100.4,1610612757,129.7,134.6,131.4,136.4,136.0,53.0,91.0,0.582,44.0,19.0,5.0,2.0,13.0,home,3.0,226.5,False,-3.0
26099,26099,26099,Jose Calderon,101181,DET @ NYK,DET,1610612765,NYK,0,21801223,2019-04-10,W,0,0,0,0,1,0.000,0,1,0.000,0,0,NaN,0,0,0,0,0,-14,0.0,0.000,0.000000,NaN,NaN,40.0,40.0,180.0,180.0,-140.0,0.000,0.000,0.000,0.000,0.000,0.00,0.100,0.000,120.50,120.50,-0.098,10.0,100.42,0.100,3.98,4.97,0.36,0,0,0,12,0,0,10,0,0,0.00,0,1,0.000,0,0,0.000,0.0,0.0,0.0,0.0,7.0,0.0,0.0,2.0,0.0,1.0,0.0,0,22018,Detroit Pistons,2019-04-10,DET @ NYK,W,240,41,85,0.482,14,33,0.424,19,20,0.950,11,45,56,25,5,2,14,23,115,26,1,95.9,95.9,95.9,1610612752,118.8,91.9,121.1,93.7,89.0,31.0,77.0,0.403,33.0,23.0,7.0,5.0,11.0,away,8.5,205.0,True,-8.5
26100,26100,26100,Jeremy Lamb,203087,CHA vs. ORL,CHA,1610612766,ORL,1,21801222,2019-04-10,L,22,2,8,6,12,0.500,4,7,0.571,6,6,1.000,0,8,0,0,1,-7,33.6,1.503,0.666667,NaN,NaN,117.5,117.5,132.8,132.8,-15.3,0.000,0.320,0.154,0.105,0.667,2.00,0.250,0.751,94.03,94.03,0.149,63.0,78.36,0.250,31.65,4.11,2.32,0,8,8,45,0,0,29,2,5,0.40,4,7,0.571,3,3,1.000,0.0,0.0,0.0,0.0,5.0,4.0,3.0,40.0,0.0,2.0,3.0,0,22018,Charlotte Hornets,2019-04-10,CHA vs. ORL,L,240,41,78,0.526,8,29,0.276,24,27,0.889,4,28,32,21,3,4,8,14,114,-8,1,93.8,93.8,93.8,1610612753,121.4,130.0,121.5,130.1,122.0,48.0,88.0,0.545,39.0,24.0,5.0,2.0,6.0,home,4.0,217.5,True,4.0

## Merge team data into player logs

In [4]:
# # Drop all team-related columns to re-merge with correct pace calculations
# data = s19_regular

# columns_to_drop = [
#     'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
#     # Pace columns (incorrect calculations)
#     'TEAM_PACE', 'GAME_PACE', 'OPP_PACE',
    
#     # Rating columns (may need recalculation with correct pace)
#     'TEAM_OFF_RATING', 'TEAM_DEF_RATING',
#     'OPP_OFF_RATING', 'OPP_DEF_RATING',
    
#     # Other team stats that came from the merge
#     'TEAM_PTS', 'TEAM_FGM', 'TEAM_FGA', 'TEAM_FG_PCT',
#     'TEAM_FG3M', 'TEAM_FG3A', 'TEAM_FG3_PCT',
#     'TEAM_FTM', 'TEAM_FTA', 'TEAM_FT_PCT', 
#     'TEAM_OREB', 'TEAM_DREB', 'TEAM_REB',
#     'TEAM_AST', 'TEAM_STL', 'TEAM_BLK', 'TEAM_TOV',
#     'TEAM_PF', 'TEAM_PLUS_MINUS',
    
#     # Opponent stats
#     'OPP_TEAM_ID', 'OPP_PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
#     'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK', 'OPP_TOV'
    
#     'TEAM_SEASON_ID_x',	'OPP_TOV_x', 'TEAM_SEASON_ID_y', 'OPP_TOV_y', 'TEAM_SEASON_ID', 'TEAM_NAME', 'TEAM_GAME_DATE', 'TEAM_MATCHUP', 'TEAM_WL', 'TEAM_MIN', 'VIDEO_AVAILABLE'
# ]

# # Drop columns that exist in the dataframe
# existing_cols = [col for col in columns_to_drop if col in data.columns]
# data = data.drop(columns=existing_cols)

# teamlogs = mergeTeamtoPlayer(data, season='2018-19', season_type='Regular Season')
# teamlogs

In [5]:
# teamlogs.to_csv('../DATA/CSV_FILES/REGULAR_DATA/S19.csv')
# teamlogs

## Assign features for regular season data

In [6]:
star_players_by_year = {
    2019:[ "Giannis Antetokounmpo",
    "LeBron James",
    "Anthony Davis",
    "James Harden",
    "Luka Dončić",
    "Kawhi Leonard",
    "Pascal Siakam",
    "Nikola Jokić",
    "Damian Lillard",
    "Chris Paul",
    "Jayson Tatum",
    "Jimmy Butler",
    "Rudy Gobert",
    "Ben Simmons",
    "Russell Westbrook"],
    2020:[
    "Giannis Antetokounmpo",
    "Kawhi Leonard", 
    "Nikola Jokić",
    "Stephen Curry",
    "Luka Dončić",
    "Julius Randle",
    "LeBron James",
    "Joel Embiid",
    "Chris Paul",
    "Damian Lillard",
    "Jimmy Butler",
    "Paul George",
    "Rudy Gobert",
    "Bradley Beal",
    "Kyrie Irving"
    ],
    2021: [
        "Giannis Antetokounmpo", "Kawhi Leonard", "Nikola Jokić", "Stephen Curry", "Luka Dončić",
        "Julius Randle", "LeBron James", "Joel Embiid", "Damian Lillard", "Chris Paul",
        "Jimmy Butler", "Paul George", "Rudy Gobert", "Bradley Beal", "Kyrie Irving",
        "Devin Booker", "Mike Conley", "James Harden", "Zach LaVine", "Donovan Mitchell",
        "Nikola Vucevic", "Anthony Davis"
    ],
    2022: [
        "Giannis Antetokounmpo", "Luka Dončić", "Jayson Tatum", "Nikola Jokić", "Devin Booker",
        "Ja Morant", "Stephen Curry", "DeMar DeRozan", "Kevin Durant", "Joel Embiid",
        "LeBron James", "Chris Paul", "Trae Young", "Pascal Siakam", "Karl-Anthony Towns",
        "Andrew Wiggins", "Donovan Mitchell", "Rudy Gobert", "Zach LaVine", "Khris Middleton",
        "Jimmy Butler", "Darius Garland", "Fred VanVleet", "LaMelo Ball"
    ],
    2023: [
        "Giannis Antetokounmpo", "Jayson Tatum", "Joel Embiid", "Shai Gilgeous-Alexander", "Luka Dončić",
        "Jaylen Brown", "Jimmy Butler", "Nikola Jokić", "Stephen Curry", "Donovan Mitchell",
        "LeBron James", "Julius Randle", "Domantas Sabonis", "De'Aaron Fox", "Damian Lillard",
        "Kyrie Irving", "Zion Williamson", "Kevin Durant", "Ja Morant", "DeMar DeRozan",
        "Tyrese Haliburton", "Jrue Holiday", "Bam Adebayo", "Jaren Jackson Jr.", "Paul George",
        "Pascal Siakam", "Anthony Edwards"
    ],
    2024: [
        "Shai Gilgeous-Alexander", "Luka Dončić", "Jayson Tatum", "Giannis Antetokounmpo", "Nikola Jokić",
        "Jalen Brunson", "Anthony Edwards", "Kawhi Leonard", "Kevin Durant", "Anthony Davis",
        "Stephen Curry", "Devin Booker", "LeBron James", "Domantas Sabonis", "Bam Adebayo",
        "Tyrese Haliburton", "Damian Lillard", "Karl-Anthony Towns", "Jaylen Brown",
        "Trae Young", "Paolo Banchero", "Scottie Barnes", 'Joel Embiid'
    ],
    2025: [
        'Shai Gilgeous-Alexander', 'Nikola Jokić', 'Giannis Antetokounmpo', 'Jayson Tatum', 'Donovan Mitchell',
        'Anthony Edwards', 'LeBron James', 'Stephen Curry', 'Evan Mobley', 'Jalen Brunson',
        'Cade Cunningham', 'Karl-Anthony Towns', 'Tyrese Haliburton', 'Jalen Williams', 'James Harden',
        'Darius Garland', 'Damian Lillard', 'Anthony Davis', 'Kyrie Irving', 'Jaylen Brown', 'Tyler Herro', 'Jaren Jackson Jr.', 
        'Pascal Siakam', 'Victor Wembanyama', 'Alperen Sengun', 'Trae Young', 'LaMelo Ball', 'Devin Booker', 'Joel Embiid', 'Luka Dončić'
]}

In [7]:
def process_season_features(season_df, prop_type, year, star_players):
    df = season_df.copy()
    df = sort_data_for_features(df)
    df['STARTING'] = df['START_POSITION'].apply(lambda x: 1 if x in ['G','F','C'] else 0)
    # df['BLOWOUT_RISK'] = (abs(df['spread']) >= 10).astype(int)
    df['TEAM_IMPLIED_PTS_FAV'] = ((df['total'] + df['team_spread']) / 2).round(1)
    df['TEAM_IMPLIED_PTS_UND'] = ((df['total'] - df['team_spread']) / 2).round(1)
    
    # Add position data
    cache_file = os.path.join(feature_path, 'DATA', 'TOOLS', 'playerInfo.csv')
    df = assign_position_with_cache(
        df, 
        cache_file=cache_file,
        max_workers=4, 
        delay_between_requests=1.5
    )
    # Basic features to track rest and travel
    df = add_rest_day_features(df)
    
    # Prop-specific features
    df = rollingAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE', windows=[3,5,7])
    df = statAgainstTeam(df, player_id_col='PLAYER_ID', opp_col='OPP_ABBREVIATION', stat_line=prop_type)
    df = HomeAwayAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE')
    df = getPlayerAvgToDateVectorized(df)
    df = addLagFeatures(df, stat_lines=['PTS', 'MIN', 'FGA', 'FTA', 'FG3A', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'USG_PCT', 'TS_PCT',
                        'EFG_PCT','POSS', 'TCHS','AST', 'REB', 'TOV'])
    # df = add_volatility_features(df, windows=[3,5,7,15,40])
    # df = add_performance_volatility_categories(df)
    # df = add_recent_form_volatility(df)
    df = process_star_players_data(df, star_players, min_minutes=20)
    df = add_performance_without_stars_columns(df, min_games=1)
    df = teamUsualStarters(df)
    df = oppTeamUsualStarters(df)
    # df = add_all_defensive_features(df, all_defensive_players, year)
    df = teamContext(df)
    df = assign_opponent_team_stats_dict(df)
    df = expectedPace(df)
    
    # Clean up any unwanted columns
    if 'Unnamed: 0' in df.columns:
        df.drop(columns=['Unnamed: 0'], inplace=True)
    if 'Unnamed: 0.1' in df.columns:
        df.drop(columns=['Unnamed: 0.1'], inplace=True)
    return df

prop_types = ['PTS']
data = [s19_regular,s20_regular, s21_regular,s22_regular,s23_regular,s24_regular,s25_regular]
seasons = [2019,2020,2021,2022,2023,2024,2025]

# Pre-define output directory once
output_dir = os.path.join(feature_path, 'DATA', 'CSV_FILES', 'TRAIN_DATA')
os.makedirs(output_dir, exist_ok=True)

# Process each season sequentially but with optimized operations
for season_data, year in zip(data, seasons):
    print(f"Processing year {year}...")
    
    # Process features
    processed_data = process_season_features(
        season_data, 
        prop_type='PTS',
        year=year,
        star_players=set(star_players_by_year[year]),
        # all_defensive_players=set(all_defensive_players[year])
    )
    
    # Save file
    output_path = os.path.join(output_dir, f'PTS_TRAIN_{str(year)[-2:]}.csv')
    processed_data.to_csv(output_path)
    print(f"Completed {year}")

Processing year 2019...
Loading position cache...
Loaded 992 players from cache
Found 530 unique players, 159 need to be fetched
Fetching 159 new players using 4 threads...
Fetched PLAYER_ID 1717... (1/159)
Fetched PLAYER_ID 1713... (2/159)
Fetched PLAYER_ID 2037... (3/159)
Fetched PLAYER_ID 2199... (4/159)
Fetched PLAYER_ID 2200... (5/159)
Fetched PLAYER_ID 2225... (6/159)
Fetched PLAYER_ID 2403... (7/159)
Fetched PLAYER_ID 2548... (8/159)
Fetched PLAYER_ID 2585... (9/159)
Fetched PLAYER_ID 2594... (10/159)
Fetched PLAYER_ID 2733... (11/159)
Fetched PLAYER_ID 2734... (12/159)
Fetched PLAYER_ID 2736... (13/159)
Fetched PLAYER_ID 101107... (14/159)
Fetched PLAYER_ID 2747... (15/159)
Fetched PLAYER_ID 101106... (16/159)
Fetched PLAYER_ID 101109... (17/159)
Fetched PLAYER_ID 101112... (18/159)
Fetched PLAYER_ID 101123... (19/159)
Fetched PLAYER_ID 101133... (20/159)
Fetched PLAYER_ID 101161... (21/159)
Fetched PLAYER_ID 101162... (22/159)
Fetched PLAYER_ID 101181... (23/159)
Fetched PLAYER_ID 200757... (24/159)
Fetched PLAYER_ID 201149... (25/159)
Fetched PLAYER_ID 201156... (26/159)
Fetched PLAYER_ID 201147... (27/159)
Fetched PLAYER_ID 201158... (28/159)
Fetched PLAYER_ID 201160... (29/159)
Fetched PLAYER_ID 200826... (30/159)
Fetched PLAYER_ID 201163... (31/159)
Fetched PLAYER_ID 201281... (32/159)
Fetched PLAYER_ID 201563... (33/159)
Fetched PLAYER_ID 201573... (34/159)
Fetched PLAYER_ID 201583... (35/159)
Fetched PLAYER_ID 201584... (36/159)
Fetched PLAYER_ID 201585... (37/159)
Fetched PLAYER_ID 201601... (38/159)
Fetched PLAYER_ID 201936... (39/159)
Fetched PLAYER_ID 201956... (40/159)
Fetched PLAYER_ID 201960... (41/159)
Fetched PLAYER_ID 201967... (42/159)
Fetched PLAYER_ID 201973... (43/159)
Fetched PLAYER_ID 201975... (44/159)
Fetched PLAYER_ID 202323... (45/159)
Fetched PLAYER_ID 202325... (46/159)
Fetched PLAYER_ID 202327... (47/159)
Fetched PLAYER_ID 202347... (48/159)
Fetched PLAYER_ID 202391... (49/159)
Fetched PLAYER_ID 202498... (50/159)
Fetched PLAYER_ID 202690... (51/159)
Fetched PLAYER_ID 202702... (52/159)
Fetched PLAYER_ID 202700... (53/159)
Fetched PLAYER_ID 202703... (54/159)
Fetched PLAYER_ID 202705... (55/159)
Fetched PLAYER_ID 202714... (56/159)
Fetched PLAYER_ID 202718... (57/159)
Fetched PLAYER_ID 202720... (58/159)
Fetched PLAYER_ID 203077... (59/159)
Fetched PLAYER_ID 203089... (60/159)
Fetched PLAYER_ID 203079... (61/159)
Fetched PLAYER_ID 203092... (62/159)
Fetched PLAYER_ID 203093... (63/159)
Fetched PLAYER_ID 203098... (64/159)
Fetched PLAYER_ID 203101... (65/159)
Fetched PLAYER_ID 203112... (66/159)
Fetched PLAYER_ID 203124... (67/159)
Fetched PLAYER_ID 203159... (68/159)
Fetched PLAYER_ID 203459... (69/159)
Fetched PLAYER_ID 203474... (70/159)
Fetched PLAYER_ID 203477... (71/159)
Fetched PLAYER_ID 203485... (72/159)
Fetched PLAYER_ID 203518... (73/159)
Fetched PLAYER_ID 203546... (74/159)
Fetched PLAYER_ID 203564... (75/159)
Fetched PLAYER_ID 203613... (76/159)
Fetched PLAYER_ID 203710... (77/159)
Fetched PLAYER_ID 203894... (78/159)
Fetched PLAYER_ID 203895... (79/159)
Fetched PLAYER_ID 204066... (80/159)
Fetched PLAYER_ID 203584... (81/159)
Fetched PLAYER_ID 203961... (82/159)
Fetched PLAYER_ID 1626154... (83/159)
Fetched PLAYER_ID 1626170... (84/159)
Fetched PLAYER_ID 1626185... (85/159)
Fetched PLAYER_ID 1626150... (86/159)
Fetched PLAYER_ID 1626209... (87/159)
Fetched PLAYER_ID 1626203... (88/159)
Fetched PLAYER_ID 1626210... (89/159)
Fetched PLAYER_ID 1626257... (90/159)
Fetched PLAYER_ID 1626259... (91/159)
Fetched PLAYER_ID 1626296... (92/159)
Fetched PLAYER_ID 1627215... (93/159)
Fetched PLAYER_ID 1627395... (94/159)
Fetched PLAYER_ID 1627733... (95/159)
Fetched PLAYER_ID 1627735... (96/159)
Fetched PLAYER_ID 1627738... (97/159)
Fetched PLAYER_ID 1627743... (98/159)
Fetched PLAYER_ID 1627753... (99/159)
Fetched PLAYER_ID 1627755... (100/159)
Fetched PLAYER_ID 1627758... (101/159)
Fetched PLAYER_ID 1627772... (102/159)
Fetched PLAYER_ID 1627781... (103/159)
Fetched PLAYER_ID 1627790... (104/159)
Fetched PLAYER_ID 1627786... (105/159)
Fetched PLAYER_ID 1627816... (106/159)
Fetched PLAYER_ID 1627855... (107/159)
Fetched PLAYER_ID 1627883... (108/159)
Fetched PLAYER_ID 1628070... (109/159)
Fetched PLAYER_ID 1628249... (110/159)
Fetched PLAYER_ID 1628387... (111/159)
Fetched PLAYER_ID 1628393... (112/159)
Fetched PLAYER_ID 1628397... (113/159)
Fetched PLAYER_ID 1628399... (114/159)
Fetched PLAYER_ID 1628403... (115/159)
Fetched PLAYER_ID 1628405... (116/159)
Fetched PLAYER_ID 1628413... (117/159)
Fetched PLAYER_ID 1628417... (118/159)
Fetched PLAYER_ID 1628421... (119/159)
Fetched PLAYER_ID 1628443... (120/159)
Fetched PLAYER_ID 1628439... (121/159)
Fetched PLAYER_ID 1628462... (122/159)
Fetched PLAYER_ID 1628463... (123/159)
Fetched PLAYER_ID 1628469... (124/159)
Fetched PLAYER_ID 1628505... (125/159)
Fetched PLAYER_ID 1628513... (126/159)
Fetched PLAYER_ID 1628515... (127/159)
Fetched PLAYER_ID 1628518... (128/159)
Fetched PLAYER_ID 1628605... (129/159)
Fetched PLAYER_ID 1628656... (130/159)
Fetched PLAYER_ID 1628769... (131/159)
Fetched PLAYER_ID 1628959... (132/159)
Fetched PLAYER_ID 1628979... (133/159)
Fetched PLAYER_ID 1628980... (134/159)
Fetched PLAYER_ID 1628999... (135/159)
Fetched PLAYER_ID 1629015... (136/159)
Fetched PLAYER_ID 1629016... (137/159)
Fetched PLAYER_ID 1629019... (138/159)
Fetched PLAYER_ID 1629045... (139/159)
Fetched PLAYER_ID 1629053... (140/159)
Fetched PLAYER_ID 1629055... (141/159)
Fetched PLAYER_ID 1629058... (142/159)
Fetched PLAYER_ID 1629059... (143/159)
Fetched PLAYER_ID 1629061... (144/159)
Fetched PLAYER_ID 1629093... (145/159)
Fetched PLAYER_ID 1629094... (146/159)
Fetched PLAYER_ID 1629102... (147/159)
Fetched PLAYER_ID 1629116... (148/159)
Fetched PLAYER_ID 1629118... (149/159)
Fetched PLAYER_ID 1629122... (150/159)
Fetched PLAYER_ID 1629123... (151/159)
Fetched PLAYER_ID 1629140... (152/159)
Fetched PLAYER_ID 1629133... (153/159)
Fetched PLAYER_ID 1629151... (154/159)
Fetched PLAYER_ID 1629147... (155/159)
Fetched PLAYER_ID 1629152... (156/159)
Fetched PLAYER_ID 1629155... (157/159)
Fetched PLAYER_ID 1629353... (158/159)
Fetched PLAYER_ID 1629541... (159/159)
Saving updated cache...
Cache saved with 1151 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2019
Processing year 2020...
Loading position cache...
Loaded 1151 players from cache
Found 529 unique players, 24 need to be fetched
Fetching 24 new players using 4 threads...
Fetched PLAYER_ID 1626187... (1/24)
Fetched PLAYER_ID 1627784... (2/24)
Fetched PLAYER_ID 202951... (3/24)
Fetched PLAYER_ID 203705... (4/24)
Fetched PLAYER_ID 1628430... (5/24)
Fetched PLAYER_ID 1627982... (6/24)
Fetched PLAYER_ID 1628450... (7/24)
Fetched PLAYER_ID 1628499... (8/24)
Fetched PLAYER_ID 1628987... (9/24)
Fetched PLAYER_ID 1628985... (10/24)
Fetched PLAYER_ID 1629044... (11/24)
Fetched PLAYER_ID 1629065... (12/24)
Fetched PLAYER_ID 1629598... (13/24)
Fetched PLAYER_ID 1629608... (14/24)
Fetched PLAYER_ID 1629625... (15/24)
Fetched PLAYER_ID 1629621... (16/24)
Fetched PLAYER_ID 1629668... (17/24)
Fetched PLAYER_ID 1629724... (18/24)
Fetched PLAYER_ID 1629729... (19/24)
Fetched PLAYER_ID 1629734... (20/24)
Fetched PLAYER_ID 1629739... (21/24)
Fetched PLAYER_ID 1629741... (22/24)
Fetched PLAYER_ID 1629745... (23/24)
Fetched PLAYER_ID 1629742... (24/24)
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2020
Processing year 2021...
Loading position cache...
Loaded 1175 players from cache
Found 540 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2021
Processing year 2022...
Loading position cache...
Loaded 1175 players from cache
Found 605 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2022
Processing year 2023...
Loading position cache...
Loaded 1175 players from cache
Found 539 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2023
Processing year 2024...
Loading position cache...
Loaded 1175 players from cache
Found 572 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2024
Processing year 2025...
Loading position cache...
Loaded 1175 players from cache
Found 569 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!

/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[rolling_col_name] = rolling_avg.fillna(df[expanding_col])
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[season_avg_col] = df.groupby(player_id_col)[col].transform(
/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor/FEATURE_ENGINEERING/features.py:859: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('PLAYER_NAME', group_keys=False).apply(calculate_without_star_stats)

Completed 2025

In [8]:
# df = s21

# df['STARTING'] = df['START_POSITION'].apply(lambda x: 1 if x in ['G','F','C'] else 0)
# df['team_is_favored'] = df['team_is_favored'].astype(int)
# df['whos_favored'] = df['whos_favored'].apply(lambda x: 1 if x == 'home' else 0)
# df['BLOWOUT_RISK'] = (abs(df['spread']) >= 10).astype(int)

# # Add position data
# cache_file = os.path.join(feature_path, 'DATA', 'TOOLS', 'playerInfo.csv')
# df = assign_position_with_cache(
#     df, 
#     cache_file=cache_file,
#     max_workers=4, 
#     delay_between_requests=1.5
# )
# df = add_rest_day_features(df)
# df = add_minutes_trend_features(df)
# df = add_lineup_cohesion(df)
# df = add_rotation_stability(df)
# df = add_usage_shift(df)
# df = MINrollingAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE', windows=[3,5,7])
# df = MINLagFeatures(df, player_id_col='PLAYER_ID', date_col='GAME_DATE', stat_line='MIN')
# df = getPlayerMINAvgToDate(df, player_id_col='PLAYER_ID', date_col='GAME_DATE')
# df = MINHomeAwayAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE')
# df = MINAgainstTeam(df, player_id_col='PLAYER_ID', opp_col='OPP_ABBREVIATION', stat_line='MIN')
# df = assign_opponent_team_stats_dict(df)
# df = teamContext(df)
# df.to_csv('../DATA/CSV_FILES/TRAIN_DATA/MIN_TRAIN_21.csv', index=False)

In [9]:
def merge_betting_data(player_df, betting_df, team_dict):
    """
    Merge betting data (spread, total, who's favored) into player dataset
    """
    df = player_df.copy()
    odds = betting_df.copy()
    df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'])
    odds['date'] = pd.to_datetime(odds['date'])
    
    # Convert betting data team abbreviations to uppercase using team_dict
    odds['away_upper'] = odds['away'].map(team_dict)
    odds['home_upper'] = odds['home'].map(team_dict)
    
    # First, create a unique identifier for each game in odds data
    odds['game_key_home'] = odds['date'].astype(str) + '_' + odds['home_upper'] + '_' + odds['away_upper']
    odds['game_key_away'] = odds['date'].astype(str) + '_' + odds['away_upper'] + '_' + odds['home_upper']
    
    df['game_key'] = df['GAME_DATE'].astype(str) + '_' + df['TEAM_ABBREVIATION'] + '_' + df['OPP_ABBREVIATION']
    home_merge = df.merge(
        odds[['game_key_home', 'whos_favored', 'spread', 'total']].rename(columns={'game_key_home': 'game_key'}),
        on='game_key',
        how='left',
        suffixes=('', '_home')
    )
    away_merge = df.merge(
        odds[['game_key_away', 'whos_favored', 'spread', 'total']].rename(columns={'game_key_away': 'game_key'}),
        on='game_key', 
        how='left',
        suffixes=('', '_away')
    )
    df['whos_favored'] = home_merge['whos_favored'].fillna(away_merge['whos_favored'])
    df['spread'] = home_merge['spread'].fillna(away_merge['spread']).round(2)
    df['total'] = home_merge['total'].fillna(away_merge['total']).round(2)
    df['team_is_favored'] = ((df['whos_favored'] == 'home') & (df['HOME_GAME'] == 1)) | \
                           ((df['whos_favored'] == 'away') & (df['HOME_GAME'] == 0))
    df['team_spread'] = df.apply(lambda row: 
        round(row['spread'] if row['HOME_GAME'] == 1 else -row['spread'], 2), axis=1)
    df.drop('game_key', axis=1, inplace=True)
    return df

team_dict = {
    'min': 'MIN', 
    'bos': 'BOS', 
    'bkn': 'BKN', 
    'ny': 'NYK', 
    'phi': 'PHI', 
    'tor': 'TOR', 
    'chi': 'CHI', 
    'cle': 'CLE', 
    'det': 'DET', 
    'ind': 'IND', 
    'mia': 'MIA', 
    'atl': 'ATL', 
    'cha': 'CHA', 
    'was': 'WAS',
    'wsh': 'WAS',
    'orl': 'ORL', 
    'mil': 'MIL', 
    'chh': 'CHH', 
    'dal': 'DAL', 
    'hou': 'HOU',
    'lac': 'LAC',
    'lal': 'LAL',
    'sac': 'SAC',
    'por': 'POR',
    'uta': 'UTA',
    'utah': 'UTA', 
    'den': 'DEN',
    'okc': 'OKC',
    'mem': 'MEM',
    'no': 'NOP',
    'sa': 'SAS',    
    'gs': 'GSW',
    'phx': 'PHX',  
}

In [10]:
bettingData = pd.read_csv('../DATA/CSV_FILES/bettingData.csv')
df = merge_betting_data(s20_regular, bettingData, team_dict)
df

,Unnamed: 0.1,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,whos_favored,spread,total,team_is_favored,team_spread
0,0,0,Derrick Favors,202324,NOP @ TOR,NOP,1610612740,TOR,0,21900001,2019-10-22,L,6,2,7,3,6,0.500,0,0,NaN,0,0,NaN,1,6,0,1,1,-12,19.4,1.000,0.500000,C,NaN,108.2,108.2,132.7,132.7,-24.5,0.048,0.261,0.159,0.118,0.500,2.0,0.137,0.500,113.31,113.31,0.056,49,94.43,0.137,20.75,4.60,1.75,4,8,10,43,0,0,35,3,3,1.000,0,3,0.000,7,8,0.875,0.0,2.0,0.0,6.0,12.0,11.0,7.0,32.0,0.0,5.0,0.0,0,22019,New Orleans Pelicans,2019-10-22,NOP @ TOR,L,265,43,102,0.422,19,45,0.422,17,20,0.850,16,37,53,30,4,9,19,34,122,-8,1,106.2,106.2,106.2,1610612761,107.2,114.2,101.1,107.7,130.0,42.0,103.0,0.408,57.0,23.0,7.0,3.0,17.0,home,6.5,229.5,False,-6.5
1,1,1,Brandon Ingram,1627742,NOP @ TOR,NOP,1610612740,TOR,0,21900001,2019-10-22,L,22,5,5,8,19,0.421,2,5,0.400,4,4,1.0,0,5,1,2,2,-19,42.5,1.060,0.473684,F,NaN,102.6,102.6,122.5,122.5,-19.9,0.000,0.125,0.068,0.227,0.474,2.5,0.272,0.530,107.35,107.35,0.112,77,89.46,0.272,35.10,4.33,2.78,1,9,9,69,2,0,46,5,9,0.556,3,10,0.300,4,8,0.500,3.0,0.0,3.0,8.0,16.0,14.0,14.0,44.0,0.0,4.0,6.0,0,22019,New Orleans Pelicans,2019-10-22,NOP @ TOR,L,265,43,102,0.422,19,45,0.422,17,20,0.850,16,37,53,30,4,9,19,34,122,-8,1,106.2,106.2,106.2,1610612761,107.2,114.2,101.1,107.7,130.0,42.0,103.0,0.408,57.0,23.0,7.0,3.0,17.0,home,6.5,229.5,False,-6.5
2,2,2,Josh Hart,1628404,NOP @ TOR,NOP,1610612740,TOR,0,21900001,2019-10-22,L,15,1,10,4,9,0.444,3,5,0.600,4,4,1.0,4,6,0,1,1,-1,30.5,1.394,0.611111,NaN,NaN,105.5,105.5,101.7,101.7,3.7,0.111,0.167,0.139,0.067,0.611,1.0,0.174,0.697,96.28,96.28,0.213,55,80.24,0.174,28.17,4.31,2.22,5,8,13,42,0,0,27,2,5,0.400,2,4,0.500,2,4,0.500,0.0,4.0,2.0,2.0,10.0,5.0,12.0,22.0,1.0,4.0,4.0,0,22019,New Orleans Pelicans,2019-10-22,NOP @ TOR,L,265,43,102,0.422,19,45,0.422,17,20,0.850,16,37,53,30,4,9,19,34,122,-8,1,106.2,106.2,106.2,1610612761,107.2,114.2,101.1,107.7,130.0,42.0,103.0,0.408,57.0,23.0,7.0,3.0,17.0,home,6.5,229.5,False,-6.5
3,3,3,Lou Williams,101150,LAC vs. LAL,LAC,1610612746,LAL,1,21900002,2019-10-22,W,21,7,5,8,14,0.571,1,4,0.250,4,4,1.0,1,4,1,0,2,13,38.5,1.332,0.607143,NaN,NaN,121.6,121.6,102.7,102.7,19.0,0.029,0.098,0.066,0.280,0.607,3.5,0.214,0.666,97.38,97.38,0.195,74,81.15,0.214,36.72,3.76,2.46,1,5,6,89,0,2,62,1,2,0.500,7,12,0.583,0,1,0.000,8.0,2.0,5.0,6.0,9.0,6.0,5.0,30.0,1.0,0.0,9.0,0,22019,LA Clippers,2019-10-22,LAC vs. LAL,W,240,42,81,0.519,11,31,0.355,17,24,0.708,11,34,45,24,8,5,14,25,112,10,1,97.4,97.4,97.4,1610612747,118.4,107.9,111.7,101.8,102.0,37.0,85.0,0.435,41.0,20.0,4.0,7.0,15.0,away,3.5,224.0,False,3.5
4,4,4,Patrick Beverley,201976,LAC vs. LAL,LAC,1610612746,LAL,1,21900002,2019-10-22,W,2,6,10,1,7,0.143,0,5,0.000,0,0,NaN,2,8,0,1,2,13,24.0,0.286,0.142857,G,NaN,120.0,120.0,100.0,100.0,20.0,0.074,0.276,0.179,0.207,0.143,3.0,0.122,0.143,99.51,99.51,0.048,65,82.93,0.122,31.35,4.24,2.37,4,11,13,62,2,0,51,1,2,0.500,0,5,0.000,1,2,0.500,0.0,0.0,0.0,2.0,13.0,0.0,0.0,20.0,1.0,4.0,2.0,0,22019,LA Clippers,2019-10-22,LAC vs. LAL,W,240,42,81,0.519,11,31,0.355,17,24,0.708,11,34,45,24,8,5,14,25,112,10,1,97.4,97.4,97.4,1610612747,118.4,107.9,111.7,101.8,102.0,37.0,85.0,0.435,41.0,20.0,4.0,7.0,15.0,away,3.5,224.0,False,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22388,22388,22388,Nikola Jokić,203999,DEN @ TOR,DEN,1610612743,TOR,0,21901318,2020-08-14,L,2,2,1,1,1,1.000,0,0,NaN,0,0,NaN,0,1,0,0,1,-6,5.2,2.000,1.000000,C,NaN,109.5,109.5,145.0,145.0,-35.5,0.000,0.167,0.063,0.250,1.000,2.0,0.083,1.000,96.47,96.47,0.074,21,80.39,0.083,10.20,3.90,0.70,0,2,2,31,1,0,26,0,0,0.000,1,1,1.000,0,0,0.000,0.0,0.0,0.0,0.0,7.0,5.0,8.0,14.0,0.0,0.0,1.0,0,22019,Denver Nuggets,2020-08-14,DEN @ TOR,L,240,36,87,0.414,16,38,0.421,21,23,0.913,9,32,41,27,9,11,16,15,109,-8,1,103.1,103.1,103.1,1610612761,104.7,112.4,106.7,114.5,117.0,45.0,90.0,0.500,51.0,27.0,8.0,5.0,19.0,away,2.5,223.5,True,-2.5
22389,22389,22389,P.J. Tucker,200782,HOU vs. PHI,HOU,1610612745,PHI,1,21901315,2020-08-14,L,7,2,1,3,6,0.500,1,4,0.250,0,0,NaN,0,1,0,1,0,-12,14.2,1.167,0.583333,F,NaN,111.7,111.7,129.5,129.5,-17.8,0.000,0.043,0.022,0.095,0.583,0.0,0.098,0.583,99.97,99.97,0.039,60,83.30,0.098,29.05,3.76,1.93,2,4,6,31,0,0,25,1,1,1.000,2,5,0.400,1,2,0.500,0.0,0.0,0.0,4.0,16.0,8.0,9.0,36.0,1.0,2.0,1.0,0,22019,Houston Rockets,2020-08-14,HOU vs. PHI,L,240,35,80,0.438,12,48,0.250,14,16,0.875,1,26,27,25,10,9,17,18,96,-38,1,103.9,103.9,103.9,1610612755,93.2,130.0,91.7,128.0,134.0,49.0,87.0,0.563,51.0,31.0,8.0,4.0,16.0,home,2.5,230.5,True,2.5
22390,22390,22390,Eric Gordon,201569,HOU vs. PHI,HOU,1610612745,PHI,1,21901315,2020-08-14,L,13,2,2,4,10,0.400,3,6,0.500,2,2,1.0,0,2,0,1,1,-12,20.4,1.195,0.550000,G,NaN,108.0,108.0,134.7,134.7,-26.7,0.000,0.105,0.054,0.133,0.550,2.0,0.235,0.597,101.54,101.54,0.079,50,84.62,0.235,23.40,3.80,1.56,0,2,2,36,0,0,22,1,3,0.333,3,7,0.429,2,3,0.667,0.0,0.0,3.0,2.0,14.0,6.0,7.0,32.0,0.0,1.0,5.0,0,22019,Houston Rockets,2020-08-14,HOU vs. PHI,L,240,35,80,0.438,12,48,0.250,14,16,0.875,1,26,27,25,10,9,17,18,96,-38,1,103.9,103.9,103.9,1610612755,93.2,130.0,91.7,128.0,134.0,49.0,87.0,0.563,51.0,31.0,8.0,4.0,16.0,home,2.5,230.5,True,2.5
22391,22391,22391,Andre Roberson,203460,OKC @ LAC,OKC,1610612760,LAC,0,21901317,2020-08-14,L,3,2,5,1,9,0.111,0,6,0.000,1,2,0.5,1,4,0,1,0,6,15.0,0.304,0.111111,NaN,NaN,90.3,90.3,83.3,83.3,7.0,0.027,0.143,0.077,0.100,0.111,0.0,0.141,0.152,104.14,104.14,-0.041,62,86.78,0.141,28.12,4.41,2.23,3,6,9,30,0,0,21,1,3,0.333,0,6,0.000,2,2,1.000,0.0,2.0,0.0,2.0,10.0,3.0,8.0,18.0,0.0,4.0,1.0,0,22019,Oklahoma City Thunder,2020-08-14,OKC @ LAC,L,265,38,106,0.358,14,44,0.318,13,22,0.591,11,37,48,18,5,6,16,29,103,-4,1,105.9,105.9,105.9,1610612746,85.3,88.7,91.0,94.6,107.0,34.0,85.0,0.400,61.0,23.0,10.0,2.0,23.0,home,3.0,224.5,False,-3.0
22392,22392,22392,Terence Davis,1629056,TOR vs. DEN,TOR,1610612761,DEN,1,21901318,2020-08-14,W,14,3,6,5,15,0.333,2,6,0.333,2,2,1.0,1,5,2,0,3,6,28.7,0.882,0.400000,G,NaN,116.2,116.2,105.8,105.8,10.4,0.029,0.135,0.083,0.115,0.400,1.0,0.232,0.441,96.61,96.61,0.067,68,80.51,0.232,34.03,4.23,2.57,2,9,10,62,2,0,43,1,6,0.167,4,9,0.444,1,1,1.000,7.0,0.0,6.0,6.0,14.0,11.0,22.0,24.0,3.0,2.0,1.0,0,22019,Toronto Raptors,2020-08-14,TOR vs. DEN,W,240,45,90,0.500,18,35,0.514,9,14,0.643,13,38,51,27,8,5,19,24,117,8,1,103.1,103.1,103.1,1610612743,114.5,106.7,112.4,104.7,109.0,36.0,87.0,0.414,41.0,27.0,9.0,11.0,16.0,away,2.5,223.5,False,2.5