In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sys
import os


feature_path = os.path.abspath(r"C:\Users\alexg\OneDrive\Documents\NBA-Prop-Predictor")
# feature_path = os.path.abspath('/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor')
if feature_path not in sys.path:
    sys.path.append(feature_path)

from FEATURES.features import *
from PROPS_EV.calculateEVS import *
from BACKTEST.backtest import *
from MODELS.pipeline import *

### Load Model

In [2]:
model = joblib.load('Models/xgbModel.pkl')
features = joblib.load('Models/top_features.pkl')

### Load Data

In [3]:
pd.set_option('display.max_columns', None)


s25 = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_25.csv')
s24 = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_24.csv')

df = pd.concat([s25, s24]).sort_values(by='GAME_DATE')


date = '2025-03-12'
df = df[df['GAME_DATE'] < date]

dfsData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/dfs_data.csv')
dfsData = dfsData[(dfsData['BOOKMAKER'] == 'prizepicks') & (dfsData['GAME_DATE'] == date) & (dfsData['CATEGORY'] == 'player_points')]
df.tail()

C:\Users\alexg\AppData\Local\Temp\ipykernel_27840\352106883.py:13: DtypeWarning: Columns (11,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  dfsData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/dfs_data.csv')

,Unnamed: 0,Unnamed: 0.2,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,E_OFF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_SEASON_ID_x,whos_favored,spread,total,team_is_favored,team_spread,OPP_BLOWOUT_RISK,TEAM_NAME,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,AGE,FREQ_FG3,FG3M_main,FG3A_main,FG3_PCT_main,NS_FG3_PCT,PLUS_MINUS_FG3,FREQ_FG2,FG2M,FG2A,FG2_PCT,NS_FG2_PCT,PLUS_MINUS_FG2,FREQ_LT_06,FGM_LT_06,FGA_LT_06,LT_06_PCT,NS_LT_06_PCT,PLUS_MINUS_LT_06,FREQ_LT_10,FGM_LT_10,FGA_LT_10,LT_10_PCT,NS_LT_10_PCT,PLUS_MINUS_LT_10,FREQ_GT_15,FGM_GT_15,FGA_GT_15,GT_15_PCT,NS_GT_15_PCT,PLUS_MINUS_GT_15,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,STARTING,BLOWOUT_RISK,TEAM_IMPLIED_PTS_FAV,TEAM_IMPLIED_PTS_UND,HEIGHT,WEIGHT,GUARD,FORWARD,CENTER,TEAM_DAYS_REST,PLAYER_DAYS_REST,TEAM_B2B,IS_BACK_TO_BACK,PLAYER_MISSED_LAST,TEAM_GUARD_DEF_FG_PCT_ALLOWED,TEAM_GUARD_DEF_3PT_PCT_ALLOWED,TEAM_GUARD_PTS_ALLOWED_PER_MIN,TEAM_FORWARD_DEF_FG_PCT_ALLOWED,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED,TEAM_FORWARD_PTS_ALLOWED_PER_MIN,TEAM_CENTER_DEF_FG_PCT_ALLOWED,TEAM_CENTER_DEF_3PT_PCT_ALLOWED,TEAM_CENTER_PTS_ALLOWED_PER_MIN,OPP_GUARD_DEF_FG_PCT_ALLOWED,OPP_GUARD_DEF_3PT_PCT_ALLOWED,OPP_GUARD_PTS_ALLOWED_PER_MIN,OPP_FORWARD_DEF_FG_PCT_ALLOWED,OPP_FORWARD_DEF_3PT_PCT_ALLOWED,OPP_FORWARD_PTS_ALLOWED_PER_MIN,OPP_CENTER_DEF_FG_PCT_ALLOWED,OPP_CENTER_DEF_3PT_PCT_ALLOWED,OPP_CENTER_PTS_ALLOWED_PER_MIN,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_GUARD_FREQ_FG3,TEAM_GUARD_FG3_PCT_main,TEAM_GUARD_NS_FG3_PCT,TEAM_GUARD_PLUS_MINUS_FG3,TEAM_GUARD_FREQ_FG2,TEAM_GUARD_FG2_PCT,TEAM_GUARD_NS_FG2_PCT,TEAM_GUARD_PLUS_MINUS_FG2,TEAM_GUARD_FREQ_LT_06,TEAM_GUARD_LT_06_PCT,TEAM_GUARD_NS_LT_06_PCT,TEAM_GUARD_PLUS_MINUS_LT_06,TEAM_GUARD_FREQ_LT_10,TEAM_GUARD_LT_10_PCT,TEAM_GUARD_NS_LT_10_PCT,TEAM_GUARD_PLUS_MINUS_LT_10,TEAM_GUARD_FREQ_GT_15,TEAM_GUARD_GT_15_PCT,TEAM_GUARD_NS_GT_15_PCT,TEAM_GUARD_PLUS_MINUS_GT_15,TEAM_FORWARD_FREQ_FG3,TEAM_FORWARD_FG3_PCT_main,TEAM_FORWARD_NS_FG3_PCT,TEAM_FORWARD_PLUS_MINUS_FG3,TEAM_FORWARD_FREQ_FG2,TEAM_FORWARD_FG2_PCT,TEAM_FORWARD_NS_FG2_PCT,TEAM_FORWARD_PLUS_MINUS_FG2,TEAM_FORWARD_FREQ_LT_06,TEAM_FORWARD_LT_06_PCT,TEAM_FORWARD_NS_LT_06_PCT,TEAM_FORWARD_PLUS_MINUS_LT_06,TEAM_FORWARD_FREQ_LT_10,TEAM_FORWARD_LT_10_PCT,TEAM_FORWARD_NS_LT_10_PCT,TEAM_FORWARD_PLUS_MINUS_LT_10,TEAM_FORWARD_FREQ_GT_15,TEAM_FORWARD_GT_15_PCT,TEAM_FORWARD_NS_GT_15_PCT,TEAM_FORWARD_PLUS_MINUS_GT_15,TEAM_CENTER_FREQ_FG3,TEAM_CENTER_FG3_PCT_main,TEAM_CENTER_NS_FG3_PCT,TEAM_CENTER_PLUS_MINUS_FG3,TEAM_CENTER_FREQ_FG2,TEAM_CENTER_FG2_PCT,TEAM_CENTER_NS_FG2_PCT,TEAM_CENTER_PLUS_MINUS_FG2,TEAM_CENTER_FREQ_LT_06,TEAM_CENTER_LT_06_PCT,TEAM_CENTER_NS_LT_06_PCT,TEAM_CENTER_PLUS_MINUS_LT_06,TEAM_CENTER_FREQ_LT_10,TEAM_CENTER_LT_10_PCT,TEAM_CENTER_NS_LT_10_PCT,TEAM_CENTER_PLUS_MINUS_LT_10,TEAM_CENTER_FREQ_GT_15,TEAM_CENTER_GT_15_PCT,TEAM_CENTER_NS_GT_15_PCT,TEAM_CENTER_PLUS_MINUS_GT_15,OPP_GUARD_FREQ_FG3,OPP_GUARD_FG3_PCT_main,OPP_GUARD_NS_FG3_PCT,OPP_GUARD_PLUS_MINUS_FG3,OPP_GUARD_FREQ_FG2,OPP_GUARD_FG2_PCT,OPP_GUARD_NS_FG2_PCT,OPP_GUARD_PLUS_MINUS_FG2,OPP_GUARD_FREQ_LT_06,OPP_GUARD_LT_06_PCT,OPP_GUARD_NS_LT_06_PCT,OPP_GUARD_PLUS_MINUS_LT_06,OPP_GUARD_FREQ_LT_10,OPP_GUARD_LT_10_PCT,OPP_GUARD_NS_LT_10_PCT,OPP_GUARD_PLUS_MINUS_LT_10,OPP_GUARD_FREQ_GT_15,OPP_GUARD_GT_15_PCT,OPP_GUARD_NS_GT_15_PCT,OPP_GUARD_PLUS_MINUS_GT_15,OPP_FORWARD_FREQ_FG3,OPP_FORWARD_FG3_PCT_main,OPP_FORWARD_NS_FG3_PCT,OPP_FORWARD_PLUS_MINUS_FG3,OPP_FORWARD_FREQ_FG2,OPP_FORWARD_FG2_PCT,OPP_FORWARD_NS_FG2_PCT,OPP_FORWARD_PLUS_MINUS_FG2,OPP_FORWARD_FREQ_LT_06,OPP_FORWARD_LT_06_PCT,OPP_FORWARD_NS_LT_06_PCT,OPP_FORWARD_PLUS_MINUS_LT_06,OPP_FORWARD_FREQ_LT_10,OPP_FORWARD_LT_10_PCT,OPP_FORWARD_NS_LT_10_PCT,OPP_FORWARD_PLUS_MINUS_LT_10,OPP_FORWARD_FREQ_GT_15,OPP_FORWARD_GT_15_PCT,OPP_FORWARD_NS_GT_15_PCT,OPP_FORWARD_PLUS_MINUS_GT_15,OPP_CENTER_FREQ_FG3,OPP_CENTER_FG3_PCT_main,OPP_CENTER_NS_FG3_PCT,OPP_CENTER_PLUS_MINUS_FG3,OPP_CENTER_FREQ_FG2,OPP_CENTER_FG2_PCT,OPP_CENTER_NS_FG2_PCT,OPP_CENTER_PLUS_MINUS_FG2,OPP_CENTER_FREQ_LT_06,OPP_CENTER_LT_06_PCT,OPP_CENTER_NS_LT_06_PCT,OPP_CENTER_PLUS_MINUS_LT_06,OPP_CENTER_FREQ_LT_10,OPP_CENTER_LT_10_PCT,OPP_CENTER_NS_LT_10_PCT,OPP_CENTER_PLUS_MINUS_LT_10,OPP_CENTER_FREQ_GT_15,OPP_CENTER_GT_15_PCT,OPP_CENTER_NS_GT_15_PCT,OPP_CENTER_PLUS_MINUS_GT_15,PTS_ROLLING_AVG_5,FGA_ROLLING_AVG_5,FG3A_ROLLING_AVG_5,FTM_ROLLING_AVG_5,FGM_ROLLING_AVG_5,FG3M_ROLLING_AVG_5,FG_PCT_ROLLING_AVG_5,EFG_PCT_ROLLING_AVG_5,TS_PCT_ROLLING_AVG_5,USG_PCT_ROLLING_AVG_5,E_USG_PCT_ROLLING_AVG_5,MIN_ROLLING_AVG_5,POSS_ROLLING_AVG_5,PACE_ROLLING_AVG_5,E_PACE_ROLLING_AVG_5,percentagePointsPaint_ROLLING_AVG_5,percentagePointsFreeThrow_ROLLING_AVG_5,percentageFieldGoalsAttempted2pt_ROLLING_AVG_5,percentageFieldGoalsAttempted3pt_ROLLING_AVG_5,percentagePoints2pt_ROLLING_AVG_5,percentagePoints3pt_ROLLING_AVG_5,percentagePointsMidrange2pt_ROLLING_AVG_5,percentageAssisted2pt_ROLLING_AVG_5,percentageAssisted3pt_ROLLING_AVG_5,percentageUnassisted3pt_ROLLING_AVG_5,percentageAssistedFGM_ROLLING_AVG_5,percentageUnassistedFGM_ROLLING_AVG_5,percentagePointsOffTurnovers_ROLLING_AVG_5,UFGA_ROLLING_AVG_5,DFGM_ROLLING_AVG_5,DFGA_ROLLING_AVG_5,ORBC_ROLLING_AVG_5,DRBC_ROLLING_AVG_5,RBC_ROLLING_AVG_5,DREB_PCT_ROLLING_AVG_5,SAST_ROLLING_AVG_5,CFGM_ROLLING_AVG_5,CFGA_ROLLING_AVG_5,SPD_ROLLING_AVG_5,DIST_ROLLING_AVG_5,AST_PCT_ROLLING_AVG_5,NET_RATING_ROLLING_AVG_5,PIE_ROLLING_AVG_5,PLUS_MINUS_ROLLING_AVG_5,FANTASY_PTS_ROLLING_AVG_5,PTS_2ND_CHANCE_ROLLING_AVG_5,PTS_PAINT_ROLLING_AVG_5,OPP_PTS_PAINT_ROLLING_AVG_5,PFD_ROLLING_AVG_5,STL_ROLLING_AVG_5,BLK_ROLLING_AVG_5,TOV_ROLLING_AVG_5,PF_ROLLING_AVG_5,PTS_ROLLING_AVG_10,FGA_ROLLING_AVG_10,FG3A_ROLLING_AVG_10,FTM_ROLLING_AVG_10,FGM_ROLLING_AVG_10,FG3M_ROLLING_AVG_10,FG_PCT_ROLLING_AVG_10,EFG_PCT_ROLLING_AVG_10,TS_PCT_ROLLING_AVG_10,USG_PCT_ROLLING_AVG_10,E_USG_PCT_ROLLING_AVG_10,MIN_ROLLING_AVG_10,POSS_ROLLING_AVG_10,PACE_ROLLING_AVG_10,E_PACE_ROLLING_AVG_10,percentagePointsPaint_ROLLING_AVG_10,percentagePointsFreeThrow_ROLLING_AVG_10,percentageFieldGoalsAttempted2pt_ROLLING_AVG_10,percentageFieldGoalsAttempted3pt_ROLLING_AVG_10,percentagePoints2pt_ROLLING_AVG_10,percentagePoints3pt_ROLLING_AVG_10,percentagePointsMidrange2pt_ROLLING_AVG_10,percentageAssisted2pt_ROLLING_AVG_10,percentageAssisted3pt_ROLLING_AVG_10,percentageUnassisted3pt_ROLLING_AVG_10,percentageAssistedFGM_ROLLING_AVG_10,percentageUnassistedFGM_ROLLING_AVG_10,percentagePointsOffTurnovers_ROLLING_AVG_10,UFGA_ROLLING_AVG_10,DFGM_ROLLING_AVG_10,DFGA_ROLLING_AVG_10,ORBC_ROLLING_AVG_10,DRBC_ROLLING_AVG_10,RBC_ROLLING_AVG_10,DREB_PCT_ROLLING_AVG_10,SAST_ROLLING_AVG_10,CFGM_ROLLING_AVG_10,CFGA_ROLLING_AVG_10,SPD_ROLLING_AVG_10,DIST_ROLLING_AVG_10,AST_PCT_ROLLING_AVG_10,NET_RATING_ROLLING_AVG_10,PIE_ROLLING_AVG_10,PLUS_MINUS_ROLLING_AVG_10,FANTASY_PTS_ROLLING_AVG_10,PTS_2ND_CHANCE_ROLLING_AVG_10,PTS_PAINT_ROLLING_AVG_10,OPP_PTS_PAINT_ROLLING_AVG_10,PFD_ROLLING_AVG_10,STL_ROLLING_AVG_10,BLK_ROLLING_AVG_10,TOV_ROLLING_AVG_10,PF_ROLLING_AVG_10,PTS_ROLLING_AVG_15,FGA_ROLLING_AVG_15,FG3A_ROLLING_AVG_15,FTM_ROLLING_AVG_15,FGM_ROLLING_AVG_15,FG3M_ROLLING_AVG_15,FG_PCT_ROLLING_AVG_15,EFG_PCT_ROLLING_AVG_15,TS_PCT_ROLLING_AVG_15,USG_PCT_ROLLING_AVG_15,E_USG_PCT_ROLLING_AVG_15,MIN_ROLLING_AVG_15,POSS_ROLLING_AVG_15,PACE_ROLLING_AVG_15,E_PACE_ROLLING_AVG_15,percentagePointsPaint_ROLLING_AVG_15,percentagePointsFreeThrow_ROLLING_AVG_15,percentageFieldGoalsAttempted2pt_ROLLING_AVG_15,percentageFieldGoalsAttempted3pt_ROLLING_AVG_15,percentagePoints2pt_ROLLING_AVG_15,percentagePoints3pt_ROLLING_AVG_15,percentagePointsMidrange2pt_ROLLING_AVG_15,percentageAssisted2pt_ROLLING_AVG_15,percentageAssisted3pt_ROLLING_AVG_15,percentageUnassisted3pt_ROLLING_AVG_15,percentageAssistedFGM_ROLLING_AVG_15,percentageUnassistedFGM_ROLLING_AVG_15,percentagePointsOffTurnovers_ROLLING_AVG_15,UFGA_ROLLING_AVG_15,DFGM_ROLLING_AVG_15,DFGA_ROLLING_AVG_15,ORBC_ROLLING_AVG_15,DRBC_ROLLING_AVG_15,RBC_ROLLING_AVG_15,DREB_PCT_ROLLING_AVG_15,SAST_ROLLING_AVG_15,CFGM_ROLLING_AVG_15,CFGA_ROLLING_AVG_15,SPD_ROLLING_AVG_15,DIST_ROLLING_AVG_15,AST_PCT_ROLLING_AVG_15,NET_RATING_ROLLING_AVG_15,PIE_ROLLING_AVG_15,PLUS_MINUS_ROLLING_AVG_15,FANTASY_PTS_ROLLING_AVG_15,PTS_2ND_CHANCE_ROLLING_AVG_15,PTS_PAINT_ROLLING_AVG_15,OPP_PTS_PAINT_ROLLING_AVG_15,PFD_ROLLING_AVG_15,STL_ROLLING_AVG_15,BLK_ROLLING_AVG_15,TOV_ROLLING_AVG_15,PF_ROLLING_AVG_15,PTS_ROLLING_AVG_40,FGA_ROLLING_AVG_40,FG3A_ROLLING_AVG_40,FTM_ROLLING_AVG_40,FGM_ROLLING_AVG_40,FG3M_ROLLING_AVG_40,FG_PCT_ROLLING_AVG_40,EFG_PCT_ROLLING_AVG_40,TS_PCT_ROLLING_AVG_40,USG_PCT_ROLLING_AVG_40,E_USG_PCT_ROLLING_AVG_40,MIN_ROLLING_AVG_40,POSS_ROLLING_AVG_40,PACE_ROLLING_AVG_40,E_PACE_ROLLING_AVG_40,percentagePointsPaint_ROLLING_AVG_40,percentagePointsFreeThrow_ROLLING_AVG_40,percentageFieldGoalsAttempted2pt_ROLLING_AVG_40,percentageFieldGoalsAttempted3pt_ROLLING_AVG_40,percentagePoints2pt_ROLLING_AVG_40,percentagePoints3pt_ROLLING_AVG_40,percentagePointsMidrange2pt_ROLLING_AVG_40,percentageAssisted2pt_ROLLING_AVG_40,percentageAssisted3pt_ROLLING_AVG_40,percentageUnassisted3pt_ROLLING_AVG_40,percentageAssistedFGM_ROLLING_AVG_40,percentageUnassistedFGM_ROLLING_AVG_40,percentagePointsOffTurnovers_ROLLING_AVG_40,UFGA_ROLLING_AVG_40,DFGM_ROLLING_AVG_40,DFGA_ROLLING_AVG_40,ORBC_ROLLING_AVG_40,DRBC_ROLLING_AVG_40,RBC_ROLLING_AVG_40,DREB_PCT_ROLLING_AVG_40,SAST_ROLLING_AVG_40,CFGM_ROLLING_AVG_40,CFGA_ROLLING_AVG_40,SPD_ROLLING_AVG_40,DIST_ROLLING_AVG_40,AST_PCT_ROLLING_AVG_40,NET_RATING_ROLLING_AVG_40,PIE_ROLLING_AVG_40,PLUS_MINUS_ROLLING_AVG_40,FANTASY_PTS_ROLLING_AVG_40,PTS_2ND_CHANCE_ROLLING_AVG_40,PTS_PAINT_ROLLING_AVG_40,OPP_PTS_PAINT_ROLLING_AVG_40,PFD_ROLLING_AVG_40,STL_ROLLING_AVG_40,BLK_ROLLING_AVG_40,TOV_ROLLING_AVG_40,PF_ROLLING_AVG_40,GAMES_VS_OPP,MATCHUP_AVG_MIN_LAST_3_TO_DATE,MATCHUP_AVG_MIN_LAST_5_TO_DATE,MATCHUP_AVG_MIN_LAST_10_TO_DATE,MATCHUP_AVG_MIN_LAST_15_TO_DATE,MATCHUP_AVG_FGA_LAST_3_TO_DATE,MATCHUP_AVG_FGA_LAST_5_TO_DATE,MATCHUP_AVG_FGA_LAST_10_TO_DATE,MATCHUP_AVG_FGA_LAST_15_TO_DATE,MATCHUP_AVG_FG3A_LAST_3_TO_DATE,MATCHUP_AVG_FG3A_LAST_5_TO_DATE,MATCHUP_AVG_FG3A_LAST_10_TO_DATE,MATCHUP_AVG_FG3A_LAST_15_TO_DATE,MATCHUP_AVG_FTA_LAST_3_TO_DATE,MATCHUP_AVG_FTA_LAST_5_TO_DATE,MATCHUP_AVG_FTA_LAST_10_TO_DATE,MATCHUP_AVG_FTA_LAST_15_TO_DATE,MATCHUP_AVG_PTS_LAST_3_TO_DATE,MATCHUP_AVG_PTS_LAST_5_TO_DATE,MATCHUP_AVG_PTS_LAST_10_TO_DATE,MATCHUP_AVG_PTS_LAST_15_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_3_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_5_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_10_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_15_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_3_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_5_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_10_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_15_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_3_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_5_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_10_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_15_TO_DATE,MATCHUP_AVG_POSS_LAST_3_TO_DATE,MATCHUP_AVG_POSS_LAST_5_TO_DATE,MATCHUP_AVG_POSS_LAST_10_TO_DATE,MATCHUP_AVG_POSS_LAST_15_TO_DATE,MATCHUP_AVG_TCHS_LAST_3_TO_DATE,MATCHUP_AVG_TCHS_LAST_5_TO_DATE,MATCHUP_AVG_TCHS_LAST_10_TO_DATE,MATCHUP_AVG_TCHS_LAST_15_TO_DATE,MATCHUP_AVG_PASS_LAST_3_TO_DATE,MATCHUP_AVG_PASS_LAST_5_TO_DATE,MATCHUP_AVG_PASS_LAST_10_TO_DATE,MATCHUP_AVG_PASS_LAST_15_TO_DATE,MATCHUP_AVG_SAST_LAST_3_TO_DATE,MATCHUP_AVG_SAST_LAST_5_TO_DATE,MATCHUP_AVG_SAST_LAST_10_TO_DATE,MATCHUP_AVG_SAST_LAST_15_TO_DATE,MATCHUP_AVG_FTAST_LAST_3_TO_DATE,MATCHUP_AVG_FTAST_LAST_5_TO_DATE,MATCHUP_AVG_FTAST_LAST_10_TO_DATE,MATCHUP_AVG_FTAST_LAST_15_TO_DATE,MATCHUP_AVG_TOV_LAST_3_TO_DATE,MATCHUP_AVG_TOV_LAST_5_TO_DATE,MATCHUP_AVG_TOV_LAST_10_TO_DATE,MATCHUP_AVG_TOV_LAST_15_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_3_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_5_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_10_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_15_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_3_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_5_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_10_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_15_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_3_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_5_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_10_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_15_TO_DATE,MATCHUP_AVG_PIE_LAST_3_TO_DATE,MATCHUP_AVG_PIE_LAST_5_TO_DATE,MATCHUP_AVG_PIE_LAST_10_TO_DATE,MATCHUP_AVG_PIE_LAST_15_TO_DATE,MATCHUP_AVG_SPD_LAST_3_TO_DATE,MATCHUP_AVG_SPD_LAST_5_TO_DATE,MATCHUP_AVG_SPD_LAST_10_TO_DATE,MATCHUP_AVG_SPD_LAST_15_TO_DATE,MATCHUP_AVG_DIST_LAST_3_TO_DATE,MATCHUP_AVG_DIST_LAST_5_TO_DATE,MATCHUP_AVG_DIST_LAST_10_TO_DATE,MATCHUP_AVG_DIST_LAST_15_TO_DATE,PLAYER_HOME_AVG_PTS_TO_DATE,PLAYER_AWAY_AVG_PTS_TO_DATE,PLAYER_HOME_AVG_FGA_TO_DATE,PLAYER_AWAY_AVG_FGA_TO_DATE,PLAYER_HOME_AVG_FG3A_TO_DATE,PLAYER_AWAY_AVG_FG3A_TO_DATE,PLAYER_HOME_AVG_FTM_TO_DATE,PLAYER_AWAY_AVG_FTM_TO_DATE,PLAYER_HOME_AVG_FGM_TO_DATE,PLAYER_AWAY_AVG_FGM_TO_DATE,PLAYER_HOME_AVG_FG3M_TO_DATE,PLAYER_AWAY_AVG_FG3M_TO_DATE,PLAYER_HOME_AVG_FG_PCT_TO_DATE,PLAYER_AWAY_AVG_FG_PCT_TO_DATE,PLAYER_HOME_AVG_EFG_PCT_TO_DATE,PLAYER_AWAY_AVG_EFG_PCT_TO_DATE,PLAYER_HOME_AVG_TS_PCT_TO_DATE,PLAYER_AWAY_AVG_TS_PCT_TO_DATE,PLAYER_HOME_AVG_USG_PCT_TO_DATE,PLAYER_AWAY_AVG_USG_PCT_TO_DATE,PLAYER_HOME_AVG_E_USG_PCT_TO_DATE,PLAYER_AWAY_AVG_E_USG_PCT_TO_DATE,PLAYER_HOME_AVG_MIN_TO_DATE,PLAYER_AWAY_AVG_MIN_TO_DATE,PLAYER_HOME_AVG_POSS_TO_DATE,PLAYER_AWAY_AVG_POSS_TO_DATE,PLAYER_HOME_AVG_PACE_TO_DATE,PLAYER_AWAY_AVG_PACE_TO_DATE,PLAYER_HOME_AVG_E_PACE_TO_DATE,PLAYER_AWAY_AVG_E_PACE_TO_DATE,PLAYER_HOME_AVG_percentagePointsPaint_TO_DATE,PLAYER_AWAY_AVG_percentagePointsPaint_TO_DATE,PLAYER_HOME_AVG_percentagePointsFreeThrow_TO_DATE,PLAYER_AWAY_AVG_percentagePointsFreeThrow_TO_DATE,PLAYER_HOME_AVG_percentageFieldGoalsAttempted2pt_TO_DATE,PLAYER_AWAY_AVG_percentageFieldGoalsAttempted2pt_TO_DATE,PLAYER_HOME_AVG_percentageFieldGoalsAttempted3pt_TO_DATE,PLAYER_AWAY_AVG_percentageFieldGoalsAttempted3pt_TO_DATE,PLAYER_HOME_AVG_percentagePoints2pt_TO_DATE,PLAYER_AWAY_AVG_percentagePoints2pt_TO_DATE,PLAYER_HOME_AVG_percentagePoints3pt_TO_DATE,PLAYER_AWAY_AVG_percentagePoints3pt_TO_DATE,PLAYER_HOME_AVG_percentagePointsMidrange2pt_TO_DATE,PLAYER_AWAY_AVG_percentagePointsMidrange2pt_TO_DATE,PLAYER_HOME_AVG_percentageAssisted2pt_TO_DATE,PLAYER_AWAY_AVG_percentageAssisted2pt_TO_DATE,PLAYER_HOME_AVG_percentageAssisted3pt_TO_DATE,PLAYER_AWAY_AVG_percentageAssisted3pt_TO_DATE,PLAYER_HOME_AVG_percentageUnassisted3pt_TO_DATE,PLAYER_AWAY_AVG_percentageUnassisted3pt_TO_DATE,PLAYER_HOME_AVG_percentageAssistedFGM_TO_DATE,PLAYER_AWAY_AVG_percentageAssistedFGM_TO_DATE,PLAYER_HOME_AVG_percentageUnassistedFGM_TO_DATE,PLAYER_AWAY_AVG_percentageUnassistedFGM_TO_DATE,PLAYER_HOME_AVG_percentagePointsOffTurnovers_TO_DATE,PLAYER_AWAY_AVG_percentagePointsOffTurnovers_TO_DATE,PLAYER_HOME_AVG_UFGA_TO_DATE,PLAYER_AWAY_AVG_UFGA_TO_DATE,PLAYER_HOME_AVG_DFGM_TO_DATE,PLAYER_AWAY_AVG_DFGM_TO_DATE,PLAYER_HOME_AVG_DFGA_TO_DATE,PLAYER_AWAY_AVG_DFGA_TO_DATE,PLAYER_HOME_AVG_ORBC_TO_DATE,PLAYER_AWAY_AVG_ORBC_TO_DATE,PLAYER_HOME_AVG_DRBC_TO_DATE,PLAYER_AWAY_AVG_DRBC_TO_DATE,PLAYER_HOME_AVG_RBC_TO_DATE,PLAYER_AWAY_AVG_RBC_TO_DATE,PLAYER_HOME_AVG_DREB_PCT_TO_DATE,PLAYER_AWAY_AVG_DREB_PCT_TO_DATE,PLAYER_HOME_AVG_SAST_TO_DATE,PLAYER_AWAY_AVG_SAST_TO_DATE,PLAYER_HOME_AVG_CFGM_TO_DATE,PLAYER_AWAY_AVG_CFGM_TO_DATE,PLAYER_HOME_AVG_CFGA_TO_DATE,PLAYER_AWAY_AVG_CFGA_TO_DATE,PLAYER_HOME_AVG_SPD_TO_DATE,PLAYER_AWAY_AVG_SPD_TO_DATE,PLAYER_HOME_AVG_DIST_TO_DATE,PLAYER_AWAY_AVG_DIST_TO_DATE,PLAYER_HOME_AVG_AST_PCT_TO_DATE,PLAYER_AWAY_AVG_AST_PCT_TO_DATE,PLAYER_HOME_AVG_NET_RATING_TO_DATE,PLAYER_AWAY_AVG_NET_RATING_TO_DATE,PLAYER_HOME_AVG_PIE_TO_DATE,PLAYER_AWAY_AVG_PIE_TO_DATE,PLAYER_HOME_AVG_PLUS_MINUS_TO_DATE,PLAYER_AWAY_AVG_PLUS_MINUS_TO_DATE,PLAYER_HOME_AVG_FANTASY_PTS_TO_DATE,PLAYER_AWAY_AVG_FANTASY_PTS_TO_DATE,PLAYER_HOME_AVG_PTS_2ND_CHANCE_TO_DATE,PLAYER_AWAY_AVG_PTS_2ND_CHANCE_TO_DATE,PLAYER_HOME_AVG_PTS_PAINT_TO_DATE,PLAYER_AWAY_AVG_PTS_PAINT_TO_DATE,PLAYER_HOME_AVG_OPP_PTS_PAINT_TO_DATE,PLAYER_AWAY_AVG_OPP_PTS_PAINT_TO_DATE,PLAYER_HOME_AVG_PFD_TO_DATE,PLAYER_AWAY_AVG_PFD_TO_DATE,PLAYER_HOME_AVG_STL_TO_DATE,PLAYER_AWAY_AVG_STL_TO_DATE,PLAYER_HOME_AVG_BLK_TO_DATE,PLAYER_AWAY_AVG_BLK_TO_DATE,PLAYER_HOME_AVG_TOV_TO_DATE,PLAYER_AWAY_AVG_TOV_TO_DATE,PLAYER_HOME_AVG_PF_TO_DATE,PL

In [4]:
backtestData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/singleBookies.csv')
backtestData = backtestData[(backtestData['ODDS'] <= 200) & (backtestData['ODDS'] >= -200)]
singleBookies = backtestData[(backtestData['CATEGORY'] == 'points') & (backtestData['GAME_DATE'] == date)]
singleBookies

,NAME,CATEGORY,SIDE,BOOKMAKER,LINE,ODDS,fair_line,fair_odds,GAME_DATE
127510,Dyson Daniels,points,over,espnbet,14.5,-125,14.5,100,2025-03-12
127511,Dyson Daniels,points,over,fanduel,14.5,-110,14.5,100,2025-03-12
127512,Dyson Daniels,points,over,draftkings,14.5,-120,14.5,100,2025-03-12
127513,Dyson Daniels,points,over,betmgm,14.5,-125,14.5,100,2025-03-12
127514,Dyson Daniels,points,over,betrivers,14.5,-112,14.5,100,2025-03-12
...,...,...,...,...,...,...,...,...,...
130910,Nikola Jokić,points,under,betmgm,27.5,-115,28.5,100,2025-03-12
130978,Zeke Nnaji,points,over,draftkings,4.5,110,4.5,120,2025-03-12
130982,Zeke Nnaji,points,under,draftkings,4.5,-140,4.5,-120,2025-03-12
130995,Naz Reid,points,over,betmgm,12.5,-105,11.5,100,2025-03-12
130999,Naz Reid,points,under,betmgm,12.5,-135,11.5,100,2025-03-12

### Top EVs for single bets

In [5]:
results = single_bet(
    data=df,
    bookmakers=singleBookies,
    current_date=date,
    model=model,
    features=features,
    stake=5,
    simulations=10000, 
    std_window=10,
    min_std=2.0,
    max_std=10.0
)
results.sort_values(by='EV%', ascending=False).head(10)

Processing single bets...

,NAME,BOOKMAKER,CATEGORY,LINE,ODDS,SIDE,PREDICTION,RECOMMENDATION,OVER%,UNDER%,IMPLIED PROB,EV%,KELLY FULL,KELLY HALF,KELLY QUARTER,CONFIDENCE INTERVAL
843,Naji Marshall,fanduel,points,17.5,132,over,22.574394,1,0.889,0.111,0.431,106.27,0.81,0.40,0.20,"(14.5, 30.6)"
204,Aaron Wiggins,betmgm,points,2.5,105,over,14.909143,1,1.000,0.000,0.488,105.00,1.00,0.50,0.25,"(8.7, 21.0)"
859,Julian Champagnie,betmgm,points,3.5,105,over,12.385593,1,0.973,0.027,0.488,99.49,0.95,0.47,0.24,"(3.4, 21.9)"
864,Sandro Mamukelashvili,espnbet,points,4.5,100,over,9.420444,1,0.981,0.019,0.500,96.24,0.96,0.48,0.24,"(4.7, 14.1)"
863,Sandro Mamukelashvili,betmgm,points,4.5,100,over,9.420444,1,0.980,0.020,0.500,96.08,0.96,0.48,0.24,"(4.8, 14.0)"
344,Adem Bona,espnbet,points,6.5,-110,over,10.949961,0,0.987,0.013,0.524,88.33,0.97,0.49,0.24,"(7.0, 14.8)"
889,Nickeil Alexander-Walker,betmgm,points,7.5,-105,over,13.924473,1,0.964,0.036,0.512,88.11,0.93,0.46,0.23,"(7.0, 20.8)"
310,Jamal Shead,draftkings,points,15.5,-105,under,9.180629,1,0.044,0.956,0.512,86.57,0.91,0.45,0.23,"(2.2, 16.5)"
295,Quentin Grimes,fanduel,points,18.5,-104,over,24.952139,1,0.936,0.064,0.510,83.58,0.87,0.43,0.22,"(16.6, 33.5)"
313,Jamal Shead,betrivers,points,14.5,-104,under,9.180629,1,0.080,0.920,0.510,80.56,0.84,0.42,0.21,"(2.1, 16.5)"

### Top EVs for 2 leg bets

In [6]:
results = prizepickspairsEV(
    data=df,
    bookmakers=dfsData,
    current_date=date,
    model=model,
    features=features,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=2.0,
    max_std=10.0
)
results.sort_values(by='EV%', ascending=False).head(10).reset_index(drop=True)

Processing pairs...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,SIDE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,SIDE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
0,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.051,0.949,"(0.7, 13.7)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.5, 33.3)",UNDER/OVER,1,0.8843,1.653,0.826
1,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.059,0.941,"(2.3, 16.5)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.5, 33.3)",UNDER/OVER,1,0.8765,1.630,0.815
2,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.051,0.949,"(0.7, 13.7)",Paolo Banchero,player_points,prizepicks,-137,26.5,over,17.04,UNDER,0.081,0.919,"(4.5, 30.3)",UNDER/UNDER,1,0.8726,1.618,0.809
3,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.059,0.941,"(2.3, 16.5)",Paolo Banchero,player_points,prizepicks,-137,26.5,over,17.04,UNDER,0.081,0.919,"(4.5, 30.3)",UNDER/UNDER,1,0.8650,1.595,0.797
4,Andre Drummond,player_points,prizepicks,-137,10.5,over,6.04,UNDER,0.091,0.909,"(0.9, 12.7)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.051,0.949,"(0.7, 13.7)",UNDER/UNDER,0,0.8629,1.589,0.794
5,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.051,0.949,"(0.7, 13.7)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,8.5,over,4.90,UNDER,0.094,0.906,"(0.6, 10.3)",UNDER/UNDER,0,0.8600,1.580,0.790
6,Paolo Banchero,player_points,prizepicks,-137,26.5,over,17.04,UNDER,0.081,0.919,"(4.5, 30.3)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.5, 33.3)",UNDER/OVER,1,0.8566,1.570,0.785
7,Andre Drummond,player_points,prizepicks,-137,10.5,over,6.04,UNDER,0.091,0.909,"(0.9, 12.7)",Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.059,0.941,"(2.3, 16.5)",UNDER/UNDER,0,0.8554,1.566,0.783
8,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.059,0.941,"(2.3, 16.5)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,8.5,over,4.90,UNDER,0.094,0.906,"(0.6, 10.3)",UNDER/UNDER,0,0.8525,1.557,0.779
9,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.051,0.949,"(0.7, 13.7)",Zion Williamson,player_points,prizepicks,-137,23.0,over,26.75,OVER,0.898,0.102,"(21.1, 32.5)",UNDER/OVER,0,0.8520,1.556,0.778

In [7]:
threeLeg = prizepicks3LegEV(
    data=df,
    bookmakers=dfsData,
    current_date=date,
    model=model,
    features=features,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=2.0,
    max_std=10.0
)
threeLeg.sort_values(by='EV%', ascending=False).head(10)

Processing 3-leg parlays...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,SIDE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,SIDE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,PLAYER 3,CATEGORY 3,BOOKMAKER 3,ODDS 3,LINE 3,SIDE 3,PREDICTION 3,MODEL_SIDE 3,OVER% 3,UNDER% 3,CONFIDENCE INTERVAL 3,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
23171,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.062,0.938,"(2.2, 16.6)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.6, 33.6)",UNDER/UNDER/OVER,1,0.8272,3.963,0.793
23169,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.062,0.938,"(2.2, 16.6)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Paolo Banchero,player_points,prizepicks,-137,26.5,over,17.04,UNDER,0.081,0.919,"(4.5, 30.3)",UNDER/UNDER/UNDER,1,0.8157,3.894,0.779
24548,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Paolo Banchero,player_points,prizepicks,-137,26.5,over,17.04,UNDER,0.081,0.919,"(4.5, 30.3)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.6, 33.6)",UNDER/UNDER/OVER,1,0.8109,3.866,0.773
23590,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.062,0.938,"(2.2, 16.6)",Paolo Banchero,player_points,prizepicks,-137,26.5,over,17.04,UNDER,0.081,0.919,"(4.5, 30.3)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.6, 33.6)",UNDER/UNDER/OVER,1,0.8033,3.820,0.764
7811,Andre Drummond,player_points,prizepicks,-137,10.5,over,6.04,UNDER,0.096,0.904,"(0.8, 12.6)",Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.062,0.938,"(2.2, 16.6)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",UNDER/UNDER/UNDER,0,0.8023,3.814,0.763
23178,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.062,0.938,"(2.2, 16.6)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Zion Williamson,player_points,prizepicks,-137,23.0,over,26.75,OVER,0.903,0.097,"(21.2, 32.4)",UNDER/UNDER/OVER,0,0.8012,3.807,0.761
7897,Andre Drummond,player_points,prizepicks,-137,10.5,over,6.04,UNDER,0.096,0.904,"(0.8, 12.6)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.6, 33.6)",UNDER/UNDER/OVER,0,0.7976,3.786,0.757
24573,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.6, 33.6)",Zion Williamson,player_points,prizepicks,-137,23.0,over,26.75,OVER,0.903,0.097,"(21.2, 32.4)",UNDER/OVER/OVER,0,0.7965,3.779,0.756
23158,Jamal Shead,player_points,prizepicks,-137,15.0,under,9.18,UNDER,0.062,0.938,"(2.2, 16.6)",Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,8.5,over,4.90,UNDER,0.103,0.897,"(0.7, 10.4)",UNDER/UNDER/UNDER,0,0.7960,3.776,0.755
24383,Jamison Battle,player_points,prizepicks,-137,12.5,over,5.94,UNDER,0.053,0.947,"(0.6, 13.9)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,8.5,over,4.90,UNDER,0.103,0.897,"(0.7, 10.4)",Quentin Grimes,player_points,prizepicks,-137,18.5,over,24.95,OVER,0.932,0.068,"(16.6, 33.6)",UNDER/UNDER/OVER,0,0.7914,3.748,0.750